[chore] server-runtime - update cookie
remix-run/remix pull request #10104
Opened 2024-10-13 02:59 UTC by shelldandy

Fixes  CVE-2024-47764

2024-10-14 11:12 UTC, MichaelDeBoey requested changes

2024-10-14 11:12 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +            : null
Let's make this a positive condition

```suggestion
            : cookies[name] === undefined
            ? null
            : decodeCookieValue(unsign, cookies[name], secrets)
```

2024-10-14 11:12 UTC, MichaelDeBoey commented on packages/remix-server-runtime/package.json
>      "@types/cookie": "^0.6.0",
We should also remove the types as `cookie` now provided it's own types

```suggestion
```

2024-10-14 22:31 UTC, MichaelDeBoey approved these changes

2024-10-14 22:32 UTC, MichaelDeBoey commented
@shelldandy Can you please rebase your branch onto latest `dev` & set target there as well?

This is a code change, so we need to target `dev` instead

2024-11-25 00:32 UTC, MichaelDeBoey approved these changes

2024-12-17 16:03 UTC, FKSI commented
Hi 👋 . Any update on this one? 🤔

2024-12-27 23:55 UTC, VGerris commented
hi, sorry to ask for an ETA, but is there one for this to be merged? thank you!

2025-01-03 16:42 UTC, brophdawg11 commented
I'm unsure if we can merge this in Remix v2 because it seems it might have a breaking change which would result in a breaking change for Remix v2 - see https://github.com/sveltejs/kit/pull/12767

We have updated to `cookie@1` in React Router v7 so if this is a critical vulnerability I would suggest migrating to RR v7 to get to cookie v1

2025-01-13 09:15 UTC, VGerris commented
> I'm unsure if we can merge this in Remix v2 because it seems it might have a breaking change which would result in a breaking change for Remix v2 - see [sveltejs/kit#12767](https://github.com/sveltejs/kit/pull/12767)
> 
> We have updated to `cookie@1` in React Router v7 so if this is a critical vulnerability I would suggest migrating to RR v7 to get to cookie v1

can you explain what you mean ? A recent expo-router installation shows :
```
 npm why cookie                   
cookie@0.6.0
node_modules/cookie
  cookie@"^0.6.0" from @remix-run/server-runtime@2.15.2
  node_modules/@remix-run/server-runtime
    @remix-run/server-runtime@"2.15.2" from @remix-run/node@2.15.2
    node_modules/@remix-run/node
      @remix-run/node@"^2.12.0" from @expo/server@0.5.0
      node_modules/@expo/server
        @expo/server@"^0.5.0" from expo-router@4.0.16
        node_modules/expo-router
          expo-router@"^4.0.16" from the root project
```

How would I go about applying what you suggest ?
On track for this, how would we go about implementing the change ?
Do we need : support in cookie lib ? I don't have the full picture, but I think it's important to upgrade.

2025-01-21 15:10 UTC, brophdawg11 commented
`cookie@v1.0.0` contains a breaking change from `cookie@v0.6.0`.  If Remix v2 upgraded to `cookie@1.0.0` then we would need to do so in a major semver release - which we have already done in React Router v7.  We cannot release a Remix 2.x release with this upgrade because it would break the rules of semver.

If you are unable to upgrade to React Router v7 you can override the cookie dependency using your package manager overrides feature as mentioned in the [linked issue](https://github.com/sveltejs/kit/pull/12767#issuecomment-2402562640):

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides
https://pnpm.io/package_json#pnpmoverrides

2025-01-21 15:10 UTC, closed without merging