feat(examples): react-spring
remix-run/remix pull request #1417
Opened 2022-01-08 09:18 UTC by Girish21

A simple example for integrating `react-spring` with Remix

2022-01-08 11:27 UTC, LANCENET approved these changes
😎

2022-01-08 11:31 UTC, almamariali commented
> 😎

2022-01-27 23:17 UTC, MichaelDeBoey requested changes

2022-01-27 23:17 UTC, MichaelDeBoey commented on examples/react-spring/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-02-18 00:30 UTC, kentcdodds approved these changes
Looks good to me! Thanks 👏👏

2022-02-18 00:30 UTC, merged