Sanity Example Added
remix-run/remix pull request #1437
Opened 2022-01-09 12:03 UTC by Anishpras

2022-01-12 00:32 UTC, kentcdodds requested changes
Thanks for this! It seems like this example might be a bit bigger than we normally want our examples to be. Is there a way to minimize it to something much simpler?

Also, we want our examples to be TypeScript. Can you rewrite everything to TypeScript in the example?

2022-01-12 00:32 UTC, kentcdodds commented on examples/sanity/README.md
> +# Sanity Example!
Could you update this to follow the format in the `examples/template/README.md` please?

2022-01-12 00:32 UTC, kentcdodds commented on examples/sanity/app/styles/index.css
> +/*
Could you remove irrelevant files like this one? Try to keep examples as minimal as possible (as noted in [the instructions](https://github.com/remix-run/remix/tree/main/examples#contributing)).

2022-01-12 02:52 UTC, MichaelDeBoey requested changes

2022-01-12 02:52 UTC, MichaelDeBoey commented on examples/sanity/.npmrc
> +@remix-run:registry=https://npm.remix.run
This file can be deleted

2022-01-12 02:52 UTC, MichaelDeBoey commented on examples/sanity/app/entry.server.jsx
> +import dotenv from 'dotenv'
```suggestion

import 'dotenv/config';
```

2022-01-12 02:52 UTC, MichaelDeBoey commented on examples/sanity/app/entry.server.jsx
> +
```suggestion
```

2022-01-12 20:22 UTC, kentcdodds commented
Additionally, since this was pretty much copied from @simeonGriggs' [guide on sanity](https://www.sanity.io/guides/remix-run-live-preview) we should include a link to the original guide in the README>

2022-01-13 06:57 UTC, Anishpras commented
> Additionally, since this was pretty much copied from @SimeonGriggs' [guide on sanity](https://www.sanity.io/guides/remix-run-live-preview) we should include a link to the original guide in the README.

Yes, I have done all the necessary changes and included the link to the original guide.

2022-01-13 23:33 UTC, kentcdodds commented
Whoops, unfortunately when I switched the branch from `dev` to `main` (examples should be made against the `main` branch not `dev`) that kinda messed stuff up a bit. I can clean it up for you later if you don't get to it first 😅

2022-01-14 23:57 UTC, kentcdodds approved these changes
Looks awesome. Thanks! Sorry again for messing you up...

2022-01-14 23:57 UTC, merged