docs(examples): Add routes-gen example
remix-run/remix pull request #1473
Opened 2022-01-12 20:31 UTC by sandulat

2022-01-27 23:19 UTC, MichaelDeBoey requested changes

2022-01-27 23:19 UTC, MichaelDeBoey commented on examples/routes-gen/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-02-01 21:44 UTC, kentcdodds requested changes
This looks stellar! Just the one thing as noted by @MichaelDeBoey and we'll be good to go 👍

2022-02-02 10:37 UTC, sandulat commented
Thank you @kentcdodds @MichaelDeBoey!

2022-02-03 19:02 UTC, kentcdodds approved these changes
Sweet!

2022-02-03 19:02 UTC, merged