docs(examples): Add Emotion example
remix-run/remix pull request #1485
Opened 2022-01-13 18:15 UTC by helderburato

2022-01-27 23:19 UTC, MichaelDeBoey requested changes

2022-01-27 23:19 UTC, MichaelDeBoey commented on examples/emotion/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-01-28 09:40 UTC, helderburato commented on examples/emotion/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
Thanks! :D

2022-01-30 00:09 UTC, danestves commented
Hi, can you test if this implementation works with Cloudflare Worker? I try it, but it's appearing that emotion is calling some packages that don't work in a worker

2022-02-08 21:33 UTC, kentcdodds requested changes
Thanks for taking the time here!

Could you add one or two routes to make sure that it works across those route boundaries? And double-check that `CatchBoundary` and `ErrorBoundary` on the root route will work because I'm not certain it will.

2022-02-09 11:37 UTC, helderburato commented
Hey @kentcdodds!

If I catch this well, I added two new routes `/jokes` and `/jojes/:id` and a `CatchBoundary` to the root`. Is that what you expect?

The styles still working through the routes.

2022-02-14 20:51 UTC, kentcdodds commented
My big concern is that if there's a CatchBoundary or an ErrorBoundary and those are rendered due to an error, all the styles will be removed because the `App` (where the styles are rendered) will be removed from the page. If you can verify that's not a problem then we can go forward with this. Otherwise we may need to come up with a different approach.

2022-02-15 09:32 UTC, helderburato commented
If I catch it well, I triggered a catch/error boundary into the `jokes/:jokeId` and `jokes/not-found`, like the following screenshots:
<img width="1370" alt="Screenshot 2022-02-15 at 09 29 43" src="https://user-images.githubusercontent.com/862575/154033519-9821ab77-17b7-44fe-8dd5-752c9f9878c5.png">
<img width="611" alt="Screenshot 2022-02-15 at 09 29 55" src="https://user-images.githubusercontent.com/862575/154033531-61dfd8e8-04b5-412c-bd5d-8587803ba750.png">

And the styles persist into the nested routes.

Is that what you expect @kentcdodds ?

2022-02-16 00:23 UTC, kentcdodds commented
What if you have a `CatchBoundary` and `ErrorBoundary` in the `root.tsx` file and those are rendered? My guess is the styles will all be removed in that case because the `App` (which renders the styles) will be replaced by the `CatchBoundary` and the `ErrorBoundary`.

2022-02-16 23:39 UTC, kentcdodds commented
Here are more details on the issue with CSS-in-JS: https://github.com/remix-run/remix/pull/1512#issuecomment-1042413526

2022-02-17 09:10 UTC, helderburato commented
Hi @kentcdodds, I updated the project at the commit https://github.com/remix-run/remix/pull/1485/commits/7894b95529414673990e414768a2154b2b8dec0c.

The behavior looks like this:

### Root Error
<img width="441" alt="Screenshot 2022-02-17 at 09 08 44" src="https://user-images.githubusercontent.com/862575/154442874-f51fadf1-1659-4565-aa88-917c63c74f3a.png">

### CSS Rendered
<img width="877" alt="Screenshot 2022-02-17 at 09 08 54" src="https://user-images.githubusercontent.com/862575/154442917-df84b25d-7d32-4341-9d24-df3382f5b560.png">

Is that the expected?

2022-02-17 16:25 UTC, kentcdodds commented
If it's server rendered then it works fine. But it breaks for client transitions. Can you try doing the same thing I'm doing in that video?

2022-02-17 19:26 UTC, ulentini commented
I was able to reproduce the problem and it actually breaks the client, like with other CSS-in-JS libraries.
I was also able to fix it starting from @primos63 repo (where he fixed it for ChakraUI): https://github.com/primos63/chakra-remix-example

@helderburato, let me know if you want me to make a PR to your branch.

2022-02-24 18:24 UTC, helderburato commented
What do you think about @kentcdodds ?

2022-02-24 20:20 UTC, kentcdodds requested changes
This is awesome! Could you have a section in the README that describes how the example works and why you need to interact with the cache? Also make reference to the relevant files in the example. Then this will be ready to merge. Thanks!

2022-02-25 20:30 UTC, kentcdodds approved these changes
Super 👍

This is very helpful. Thank you 👏👏

2022-02-25 20:30 UTC, merged