docs(examples): Add Stitches example
remix-run/remix pull request #1495
Opened 2022-01-14 09:38 UTC by helderburato

2022-01-27 23:20 UTC, MichaelDeBoey requested changes

2022-01-27 23:20 UTC, MichaelDeBoey commented on examples/stitches/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-01-28 09:41 UTC, helderburato commented on examples/stitches/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
Thanks! :D

2022-01-30 00:13 UTC, danestves commented
![CleanShot 2022-01-29 at 20 12 20](https://user-images.githubusercontent.com/31737273/151681833-0589912e-c103-433e-ba09-1775e372ceec.png)

I'm getting these errors if I want to use this example

2022-02-08 21:35 UTC, kentcdodds requested changes
Thanks for this too! Could you address @danestves's concern there and also the same comments I left on [the emotion example](https://github.com/remix-run/remix/pull/1485)?

> Could you add one or two routes to make sure that it works across those route boundaries? And double-check that `CatchBoundary` and `ErrorBoundary` on the root route will work because I'm not certain it will.

Thanks a ton!

2022-02-09 13:09 UTC, helderburato commented
After some research into the Stitches issues, I found two issues related to the Remix, you can read more in the following links:
https://github.com/modulz/stitches/issues/886
https://github.com/modulz/stitches/issues/908

I think, for now, Stitches has this unsolved issue related to Remix.

I read some code trying to implement Stitches + Remix, and I found that case I submitted to review, it looks weird for me, but I didn't find a proper way to solve it.

What do you think about this implementation? cc @kentcdodds

2022-02-16 23:39 UTC, kentcdodds commented
I'm guessing this will suffer from the same issue: https://github.com/remix-run/remix/pull/1512#issuecomment-1042413526

2022-02-24 20:54 UTC, kentcdodds commented
Looks like we've found a solution in #1485. Can we do the same thing here?

2022-02-24 21:42 UTC, danestves commented
I doubt that will apply to Stitches @kentcdodds because Stitches doesn't depend on `@emotion`

2022-02-24 21:48 UTC, kentcdodds commented
I was more thinking about the approach. 🤷‍♂️

2022-02-24 21:51 UTC, danestves commented
Yeah, I get it 😄 the sad thing about it is that SSR with stitches is with a function but nothing more https://stitches.dev/docs/server-side-rendering, so I guess that is something that Stitches must add

2022-02-24 21:55 UTC, helderburato commented
I agree with you @danestves, the approach applied to Emotion will not work for this case.

2022-02-26 00:50 UTC, danestves commented
Hi @eldarshamukhamedov today was launched a new version of Stitches https://github.com/modulz/stitches/releases/tag/v1.2.7

And I think that `Fix for #908: toString in hydrated group sheet` could solve the  problem using the `getCssText()` on server and client

2022-02-26 01:35 UTC, danestves commented
> Hey @danestves, I'm not familiar with Stitches, so I think you probably mis-tagged me 😅

Yeah, sorry hahaha was for @helderburato

2022-02-26 14:50 UTC, merged

2022-02-28 21:51 UTC, derekr commented on examples/stitches/app/root.tsx
> +        <style
@helderburato should this be something like:

```jsx
dangerouslySetInnerHTML={{
						__html: clientStyleData.sheet || serverStyleData,
					}}
```

I noticed with the setup as is I was getting unstyled SSR on initial load, but this seems to do the trick.