docs(examples): Add DataLoader example
remix-run/remix pull request #1535
Opened 2022-01-18 15:57 UTC by hollandThomas

2022-01-19 03:10 UTC, sergiodxa commented
Shouldn’t data loaders be created on every request? To avoid sharing cached data between users.

2022-01-19 10:23 UTC, hollandThomas commented
Yes, that's correct. It's entirely possible I'm missing something, conceptually 😅  But isn't that the case here?

2022-01-19 18:50 UTC, sergiodxa commented
> Yes, that's correct. It's entirely possible I'm missing something, conceptually 😅 But isn't that the case here?

In `examples/dataloader/app/loaders/userLoader.server.ts` you are creating the new DataLoader instance, so the instance is created once for the whole app, not on every request.

I think to use data loaders you need to create them on the server, and pass them through context, they way if a request run more than one loader (first request) it will use the same data loader, for client-side navigations since they are individual requests it will not share them which I think it's fine.

2022-01-19 19:59 UTC, hollandThomas commented
Hmm. Now I'm confused. I just moved the example to the Express version of Remix and put the loader on context:

```typescript
createRequestHandler({
  build,
  mode: MODE,
  getLoadContext: () => ({
    loaders: {
      usersById
    }
  })
})
```

Interestingly, the server _now_ caches across requests, calling `db.user.findMany` only once on the initial request:

```
Express server listening on port 3000
user#findMany
GET /users 200 - - 70.793 ms
GET /users 200 - - 19.482 ms
GET /users 200 - - 18.388 ms
GET /users 200 - - 15.159 ms
GET /users 200 - - 20.222 ms
GET /users 200 - - 16.582 ms
```

Whereas with the current implementation in this PR, the `db.user.findMany` is called on each request:

```
Remix App Server started at http://localhost:3000
user#findMany
GET /users 200 - - 51.325 ms
user#findMany
GET /users 200 - - 10.255 ms
user#findMany
GET /users 200 - - 8.496 ms
user#findMany
GET /users 200 - - 7.681 ms
user#findMany
GET /users 200 - - 6.759 ms
user#findMany
GET /users 200 - - 14.401 ms
```

2022-01-19 20:21 UTC, sergiodxa-silverback commented
@hollandThomas try in production mode, the Remix App Server is clearing the require cache on every request, so the files are required again making a new instance of the data loader.

2022-01-19 20:22 UTC, sergiodxa commented
@hollandThomas try in production mode, the Remix App Server is clearing the require cache on every request, so the files are required again making a new instance of the data loader.

2022-01-19 20:33 UTC, hollandThomas commented
Ah, my bad. It needs to be a factory that creates the loader of course

```typescript
export const createUsersByIdLoader = () =>
  new DataLoader(async (keys: Readonly<string[]>) =>
    db.user.findMany({
      where: {
        id: {
          in: keys
        }
      }
    })
  );
```

```typescript
createRequestHandler({
  build,
  mode: MODE,
  getLoadContext: () => ({
    loaders: {
      usersById: createUsersByIdLoader()
    }
  })
})
```

I will clean up, then push the updated version

2022-01-27 23:21 UTC, MichaelDeBoey requested changes

2022-01-27 23:21 UTC, MichaelDeBoey commented on examples/dataloader/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-02-08 21:45 UTC, kentcdodds approved these changes
Thanks everyone for your help on this. @hollandThomas you did a great job of making this practical and also focused. Well done. Thank you for your work on this!

2022-02-08 21:45 UTC, kentcdodds commented on examples/dataloader/README.md
> +- You don't want your data loading to be tightly coupled with your parent routes, for architectural reasons
```suggestion
- You don't want your data loading to be tightly coupled with your parent routes, for architectural reasons
- You need access to the data within the `loader`, not just the component
```

2022-02-08 21:45 UTC, merged

2022-02-17 02:00 UTC, tshddx commented
To be clear, this only works for an SSR request to `/users`, right? If we did a client-side navigation to a URL that caused 2 new nested routes to load, the client will do 1 request for each nested route, and thus no batching will occur across those 2 requests. Is my understanding correct?