example: add remix-auth-supabase oauth github demo
remix-run/remix pull request #1562
Opened 2022-01-20 00:37 UTC by rphlmr

Add remix-auth-supabase sign in with github example

2022-02-14 03:29 UTC, MichaelDeBoey requested changes

2022-02-14 03:29 UTC, MichaelDeBoey commented on examples/remix-auth-supabase/oauth-github/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-02-24 20:34 UTC, kentcdodds requested changes
Hi there! Looks like there are a number of merge conflicts. Also we want to keep the examples directory flat so please move this example to `examples/remix-auth-supabase-github`. Thanks!

2022-03-01 13:10 UTC, rphlmr commented on examples/remix-auth-supabase/oauth-github/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
thanks 👍

2022-03-01 13:28 UTC, rphlmr commented
Changes done 😇 Thanks for review

2022-03-01 22:50 UTC, kentcdodds approved these changes
Looks good to me 👍 Thanks!

2022-03-01 22:50 UTC, merged