(chore) - create Preact example
remix-run/remix pull request #1636
Opened 2022-01-24 15:29 UTC by JoviDeCroock

This PR makes a version of the `examples/basic` app leveraging Preact. The only thing that stands out here is the "hack" we have to do in Preact to make the `hydrate(x, document)` work correctly.

There's an additional fix to be found in the `remix-dev` CLI, when missing a package like `React` (or in my case Preact... Yes I forgot to install Preact :joy:) it would print out that the dev cli was missing, which had me confused for quite a while. Now it will take the first line of the error message, which is the same it was before, and leverage that to indicate the missing module.

2022-01-24 15:39 UTC, JoviDeCroock commented on examples/basic-preact/app/entry.client.tsx
> +// Temp fix
Preact currently fails when passing in `document` as that has a few nodes that aren't reconcilable 😅

2022-01-24 16:02 UTC, phiberber commented
Does this also apply Preact for production? How are you checking for Preact in the website?

2022-01-24 16:03 UTC, JoviDeCroock commented
The npm deps replace React with Preact, verified production bundles :)

2022-01-27 23:22 UTC, MichaelDeBoey requested changes

2022-01-27 23:22 UTC, MichaelDeBoey commented on examples/basic-preact/app/root.tsx
> +        {process.env.NODE_ENV === "development" ? <LiveReload /> : null}
```suggestion
        <LiveReload />
```
See #1352

2022-02-10 23:54 UTC, ryanflorence commented
We've been working (sporadically, our fault) with @developit on this. I'm going to close this but welcome it being reopened when we announce official Preact support :)

2022-02-10 23:54 UTC, closed without merging

2022-02-10 23:55 UTC, ryanflorence commented
To be clear, we will support Preact "natively". No compat layer so we can get the client bundle even smaller :)