feat: add deno template
remix-run/remix pull request #1667
Opened 2022-01-26 19:21 UTC by jacob-ebey

2022-01-26 23:47 UTC, mjackson requested changes

2022-01-26 23:47 UTC, mjackson commented on packages/create-remix/templates/deno/README.md
> +# start the remix dev server and wrangler
Update comment

2022-01-26 23:47 UTC, mjackson commented on packages/create-remix/templates/deno/package.json
> +    "dev:wrangler": "cross-env NODE_ENV=development deno run --watch --allow-net --allow-read --allow-env ./build/index.js",
Update name of dev script here

2022-01-26 23:47 UTC, mjackson commented on packages/create-remix/templates/deno/server.js
> +  mode: process.env.NODE_ENV
Let's add a global variable that our compiler knows how to substitute during the build called `REMIX_MODE`.

2022-01-26 23:47 UTC, mjackson commented on packages/remix-deno/server.ts
> +    } catch (e) {}
Let's add a comment inside the `catch` that explains why we're not handling this.

2022-01-26 23:47 UTC, mjackson commented on packages/remix-deno/sessions/fileStorage.ts
> +          // @ts-expect-error
Let's add Deno's types so we can develop Remix and use them.

2022-01-26 23:48 UTC, mjackson commented on packages/create-remix/templates/deno/server.js
> +  mode: process.env.NODE_ENV
Actually, let's just put a TODO on this line and add this var in a separate PR.

2022-01-27 02:24 UTC, LANCENET commented
Ok

2022-01-29 02:47 UTC, MichaelDeBoey requested changes

2022-01-29 02:47 UTC, MichaelDeBoey commented on packages/create-remix/templates/deno_ts/app/root.tsx
> +        {process.env.NODE_ENV === "development" && <LiveReload />}
```suggestion
        <LiveReload />
```
See #1352

2022-01-31 20:32 UTC, merged