Use `window` instead of `AbortController` to check for bad `fetcher.load` call
remix-run/remix pull request #2018
Opened 2022-02-18 03:19 UTC by zachdtaylor

This is a fix for a PR I made a while back, #1416. I created that PR while on node 14, which doesn't have `AbortController` defined as a global object. In later versions of node, however, `AbortController` is defined and thus the check I created doesn't work. This PR replaces `AbortController` with `window`, which is a more reliable way of determining if we are in node or in the browser.

2022-02-18 07:13 UTC, jacob-ebey requested changes

2022-02-18 07:13 UTC, jacob-ebey commented on packages/remix-react/transition.ts
> +    if (typeof window === "undefined") {
Please use document instead of window. Deno is a runtime we are trying to support and it has window defined in the server but not document.

2022-03-18 19:03 UTC, machour approved these changes

2023-01-23 23:13 UTC, chaance commented
This code path has since moved over to React Router since v6.4, and we do a more robust check there to be sure. https://github.com/remix-run/react-router/blob/main/packages/router/router.ts#L1487

2023-01-23 23:13 UTC, closed without merging