Bug/ancestor stop propagation button
remix-run/remix pull request #2309
Opened 2022-03-13 23:15 UTC by Penspinner

**Bug**

Added a failing test where clicking a clicking a submit button within an ancestor that stops propagation on click does not send the clicked submit button's `name` and `value` properties to the action request payload.

I think this bug was introduced from https://github.com/remix-run/remix/pull/1781, which was released in [v1.2.0](https://github.com/remix-run/remix/releases/tag/v1.2.0) because this used to work until I updated dependencies at some point.

---

**How I encountered this**

I encountered this bug through my own app. I had a modal with a form in it, and it suddenly stopped sending `{ _action: add_note }` to my action's request payload. My code looks something like this:

```tsx
import { Dialog } from '@headlessui/react'
import { Form } from 'remix'

const Page = () => {
  return (
    <Dialog>
      <Form method="post">
        <button name="_action" value="add_note">
          Add note
        </button
      </Form
    </Dialog>
  )
}

export default Page
```

And I noticed Headless UI's Dialog has an `event.stopPropagation()` on the div's `onClick`: https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L303.

2022-03-13 23:25 UTC, Penspinner commented
Related Discord thread with @ryanflorence: https://discord.com/channels/770287896669978684/950943922966900756.

2022-03-13 23:29 UTC, MichaelDeBoey requested changes

2022-03-13 23:29 UTC, MichaelDeBoey commented on integration/bug-report-test.ts
> +                <button type="submit" name="_action" value="add">Add</button>
`name` can just be `action` instead

See f47a5114bb1a208f8316d1cc86eaee25699e7457 & #2164

```suggestion
                <button type="submit" name="action" value="add">Add</button>
```

2022-03-13 23:29 UTC, MichaelDeBoey commented on integration/bug-report-test.ts
> +  expect(await app.getHtml()).toMatch('{"_action":"add"}');
```suggestion
  expect(await app.getHtml()).toMatch('{"action":"add"}');
```

2022-05-08 14:04 UTC, mcansh approved these changes

2022-05-08 14:10 UTC, merged

2022-05-08 15:01 UTC, penspinner commented
@mcansh Thanks! Another duplicated PR for this bug: https://github.com/remix-run/remix/pull/2034.