docs(examples): add Magic Link + JWT example
remix-run/remix pull request #2382
Opened 2022-03-18 18:48 UTC by jstafman

Closes: #

- [ ] Docs
- [ ] Tests

2022-03-18 19:05 UTC, MichaelDeBoey requested changes

2022-03-18 19:05 UTC, MichaelDeBoey commented on examples/magic-link-with-jwt/.gitignore
> +node_modules
Please keep this to the bear minimum like we have in the `.gitignore` file in the templates

https://github.com/remix-run/remix/blob/main/templates/remix-ts/.gitignore

2022-03-18 19:11 UTC, kentcdodds requested changes
Thanks for working on this!

Unfortunately this doesn't follow [the instructions](https://github.com/remix-run/remix/tree/main/examples#contributing) for contributing examples. Please read those and update this example to be in line with our guidelines.

2022-03-18 19:19 UTC, jstafman commented
@kentcdodds - I actually didn't realize that there were separate contribution guidelines for examples. I'll be sure to review. Thanks for pointing that out.

2022-09-05 00:04 UTC, machour commented
Closing this PR as we haven't received a response from the original author.

2022-09-05 00:04 UTC, closed without merging