add google analytics example
remix-run/remix pull request #2449
Opened 2022-03-22 18:02 UTC by cliffordfajardo

### What is the Change?
Add google analytics example based off of  https://github.com/remix-run/remix/pull/1252
This example adds logic to only render google analytics in production and not development mode & makes the google analytics scripts client only scripts

Closes: https://github.com/remix-run/remix/pull/1252

- Docs: ✅
- Tests: Not applicable

2022-03-22 18:17 UTC, cliffordfajardo commented on examples/google-analytics/app/utils/gtags.client.ts
> +};
made this a client script and added console warning messages in the functions to try & provide helpful messages

2022-03-22 23:24 UTC, kentcdodds requested changes
Thanks! Just a couple things.

2022-03-22 23:24 UTC, kentcdodds commented on examples/google-analytics/app/routes/contact.tsx
> +    >
I'm pretty sure this submit will only be `HTMLFormElement` right?
```suggestion
    e: React.SyntheticEvent<HTMLFormElement>
```

2022-03-22 23:24 UTC, kentcdodds commented on examples/google-analytics/app/routes/contact.tsx
> +  const submit = useSubmit();
This is unnecessary because the form will handle submitting by default

2022-03-22 23:24 UTC, kentcdodds commented on examples/google-analytics/app/routes/contact.tsx
> +    submit(e.currentTarget, { replace: true, method: "post" });
The form will handle submitting properly by default. We don't need this.

2022-03-23 12:56 UTC, cliffordfajardo commented
Updated - thanks for the feedback @kentcdodds

2022-03-23 23:40 UTC, kentcdodds approved these changes
Looks great! 👏👏

2022-03-23 23:40 UTC, merged

2022-04-06 15:55 UTC, as-jarett commented
@cliffordfajardo thank you for solving my problem 🙏🏼