Support nested pathless layout routes
remix-run/remix pull request #2472
Opened 2022-03-23 22:55 UTC by sergiodxa

Because pathless layouts has a uniqueRouteId being `""` this adds the whole routeId, this way nested layouts will be use the actual routeId.

Closes: #

- [ ] Docs
- [ ] Tests (pending)

2022-03-23 23:22 UTC, sergiodxa commented
Test seems to pass, but I'm not really sure if the test is correct, because this only happen on dev. At least it ensure the build for prod will not fail.

How should I write a test for the dev CLI?

2022-03-28 15:02 UTC, MichaelDeBoey requested changes

2022-03-28 15:02 UTC, MichaelDeBoey commented on integration/pathless-routes-test.ts
> +          }
See #2454

```suggestion
          import { Links, Meta, Outlet, Scripts } from "remix";
          export default function Root() {
            return (
              <html lang="en">
                <head>
                  <Meta />
                  <Links />
                </head>
                <body>
                  <main>
                    <Outlet />
                  </main>
                  <Scripts />
                </body>
              </html>
            );
          }
```

2022-03-29 22:47 UTC, MichaelDeBoey approved these changes

2022-04-05 14:35 UTC, closed without merging