Implement package manager detection
remix-run/remix pull request #2562
Opened 2022-03-31 08:44 UTC by illright

Closes: https://github.com/remix-run/blues-stack/issues/37

- [ ] Docs
- [x] Tests (partially)

This PR introduces detection of the preferred package manager by looking at the `npm_user_agent` environment variable that all popular package managers set (`npm`, `yarn`, `pnpm`).

I need some assistance with testing — I'm not sure how to mock the calls to `execSync("pnpm install", ...)`, since we're spawning another Node process that calls this function. For now, I marked these tests to be skipped.

2022-04-06 20:28 UTC, MichaelDeBoey commented
@illright Could you please rebase your branch onto latest `dev` & resolve conflicts?

2022-04-07 11:56 UTC, illright commented
@MichaelDeBoey done

2022-04-07 12:35 UTC, machour commented
This would also fix https://github.com/remix-run/remix/issues/1098, right?

2022-04-07 12:42 UTC, illright commented
Yes, it should

2022-04-07 13:26 UTC, kentcdodds requested changes
Love the direction on this. Great work!

2022-04-12 11:54 UTC, illright commented on packages/remix-dev/__tests__/cli-test.ts
> +      let projectDir = getProjectDir("yarn-create");
Done, actually that allowed me to implement the tests, which is great :)

2022-04-12 11:55 UTC, illright commented
There are two failing tests in `cli-test`, I'm not sure why they're failing. It doesn't seem to be related to my changes + they fail even on `dev`

2022-04-12 16:42 UTC, kentcdodds commented
The latest commit on `dev` passed CI: https://github.com/remix-run/remix/runs/5993726267?check_suite_focus=true

I think the failure is related to your changes: https://github.com/remix-run/remix/runs/5989818412?check_suite_focus=true#step:6:53

<img width="594" alt="image" src="https://user-images.githubusercontent.com/1500684/163012305-90bf737b-9d25-43f2-aadf-a20cd79b8927.png">

I believe we don't actually want to shell out to a package manager. We have a mock in place to make sure we don't. Maybe you forgot to update the mock? I haven't looked into it yet myself.

2022-04-12 18:17 UTC, illright commented
Ah, it was a different test failing in CI, didn't even notice. On my machine, this was passing since I actually had `pnpm` installed :)

For some reason, I get another test failing locally, `packages/remix-dev/__tests__/cli-test.ts`. This happens both on this branch and in `dev`.

<details><summary>Console dump</summary>

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Summary of all failing tests
 FAIL  packages/remix-dev/__tests__/cli-test.ts (23.704 s)
  ● remix CLI › create prompts › allows you to go through the prompts

    thrown: Object {
      "status": "timeout",
      "stderr": "- Creating your app…
    ",
? Where would you like to create your app? /tmp/remix-tests-757s57373s/my-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to chang
? Do you want me to run `npm install`? No
    ",
    }

      160 |
      161 |   describe("create prompts", () => {
    > 162 |     it("allows you to go through the prompts", async () => {
          |     ^
      163 |       let projectDir = path.join(TEMP_DIR, "my-app");
      164 |
      165 |       let proc = childProcess.spawn(

      at __tests__/cli-test.ts:162:5
      at __tests__/cli-test.ts:161:3
      at Object.<anonymous> (__tests__/cli-test.ts:60:1)

  ● remix CLI › create prompts › allows you to go through the prompts and convert to JS

    thrown: Object {
      "status": "timeout",
      "stderr": "- Creating your app…
    ",
? Where would you like to create your app? /tmp/remix-tests-757s57373s/my-js-app
    
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to chang
? Do you want me to run `npm install`? No
    ",
    }

      185 |     });
      186 |
    > 187 |     it("allows you to go through the prompts and convert to JS", async () => {
          |     ^
      188 |       let projectDir = path.join(TEMP_DIR, "my-js-app");
      189 |
      190 |       let proc = childProcess.spawn(

      at __tests__/cli-test.ts:187:5
      at __tests__/cli-test.ts:161:3
      at Object.<anonymous> (__tests__/cli-test.ts:60:1)


Test Suites: 1 failed, 1 skipped, 19 passed, 20 of 21 total
Tests:       2 failed, 4 skipped, 300 passed, 306 total
Snapshots:   65 passed, 65 total
Time:        25.097 s, estimated 31 s
Ran all test suites in 8 projects.
```

</details>

2022-04-12 18:21 UTC, kentcdodds approved these changes
Solid 👍 Thank you!

2022-04-12 18:21 UTC, merged

2022-04-22 11:13 UTC, alvinthen commented
I should have created an issue, but I'm not sure if it's an isolated case. Instead of `npm_user_agent`, on my env, it was `npm_config_user_agent`

Hence `yarn create remix` is still prompting `npm install`

2022-04-22 11:21 UTC, machour commented
@alvinthen please create an issue for this, and give more details about your env in it 🙏🏼