docs(blog) - Add necessary import
remix-run/remix pull request #2710
Opened 2022-04-09 19:49 UTC by accidentaldeveloper

Closes: #

- [ ] Docs
- [ ] Tests

2022-04-09 19:53 UTC, accidentaldeveloper commented
Encountered a missing import while following the tutorial. Haven't done full diligence yet but I definitely double checked to make sure it needed to be added.

2022-04-10 09:11 UTC, machour commented
Hi, thank you for submission! Are you done with this PR? It's still marked as a draft.

2022-04-10 20:47 UTC, accidentaldeveloper commented
> Hi, thank you for submission! Are you done with this PR? It's still marked as a draft.

@machour If you are happy with it, it can be merged but I haven't _thoroughly_ confirmed it's correctness.

2022-04-10 20:53 UTC, MichaelDeBoey requested changes

2022-04-10 20:57 UTC, accidentaldeveloper commented on docs/tutorials/blog.md
> +import { Form, json } from "@remix-run/react";
Thank you. The package is still just "remix" in the version I was running for the tutorial, so I made a guess.

2022-04-11 20:03 UTC, kentcdodds approved these changes
Super, thanks!

2022-04-11 20:03 UTC, merged