(docs) Add Gitpod QuickStart to blog tutorial
remix-run/remix pull request #2711
Opened 2022-04-09 22:15 UTC by jacobPARIS

https://github.com/remix-run/indie-stack/pull/58

2022-04-12 16:16 UTC, kentcdodds requested changes
Yeah, this is neat 👍

2022-04-12 16:16 UTC, kentcdodds commented on docs/tutorials/blog.md
> +[![Gitpod Ready-to-Code](https://img.shields.io/badge/Gitpod-Ready--to--Code-blue?logo=gitpod)](https://gitpod.io/#https://github.com/jacobPARIS/indie-stack/)
```suggestion
[![Gitpod Ready-to-Code](https://img.shields.io/badge/Gitpod-Ready--to--Code-blue?logo=gitpod)](https://gitpod.io/#https://github.com/remix-run/indie-stack)
```

Once this is merged: https://github.com/remix-run/indie-stack/pull/58

2022-04-12 22:54 UTC, andrewbrey commented
@jacobPARIS I just gave this a try against your repository branch, and noted the prisma dev migration is not done automatically at container init. That might be a nice thing to add to the setup script (like you're doing when you create the `.env` file for the user). If you did that, clicking "open in gitpod" would launch into a fully working and initialized dev environment, db and all :+1:

2022-04-13 13:29 UTC, jacobPARIS commented
> @jacobPARIS the prisma dev migration is not done automatically at container init

Good catch, that is definitely worth including

2022-04-15 22:02 UTC, kentcdodds approved these changes

2022-04-15 22:02 UTC, merged