feat(templates/deno-deploy): add new deno deploy template
remix-run/remix pull request #2824
Opened 2022-04-15 22:42 UTC by pcattori

⚠️ EXPERIMENTAL ⚠️

2022-05-19 18:31 UTC, MichaelDeBoey requested changes

2022-05-19 18:31 UTC, MichaelDeBoey commented on templates/deno/README.md
> +If you want to use this token in Github Actions, set it as a Github secret.
Correct casing is `GitHub`

```suggestion
If you want to use this token in GitHub Actions, set it as a GitHub secret.
```

2022-05-19 19:33 UTC, MichaelDeBoey approved these changes

2022-05-20 20:22 UTC, MichaelDeBoey approved these changes

2022-05-21 19:40 UTC, mcansh approved these changes
LGTM 🦕☄️

2022-05-21 19:43 UTC, merged