add(examples): add Styletron example
remix-run/remix pull request #2855
Opened 2022-04-19 02:41 UTC by sergiocarneiro

Adds a new example for how to integrate the CSS-in-JS framework [Styletron](https://styletron.org/).

2022-04-19 07:13 UTC, machour requested changes

2022-04-19 07:13 UTC, machour commented on examples/styletron/app/styletron.ts
> +  typeof window === "undefined"
```suggestion
  typeof document === "undefined"
```

For deno support, see https://remix.run/docs/en/v1/pages/gotchas#typeof-window-checks

2022-04-19 12:16 UTC, machour approved these changes

2022-04-20 15:44 UTC, kentcdodds approved these changes
Thanks!

2022-04-20 15:44 UTC, merged