added nested object for form solution, using Ramda
remix-run/remix pull request #2865
Opened 2022-04-19 14:39 UTC by alireza-bonab

Closes: Here is a solution to have nested structured object out of HTML form using [Ramda js](https://ramdajs.com/)

- [x] Docs
- [ ] Tests

2022-04-29 14:55 UTC, chaance requested changes
I think we'd prefer to keep detailed implementations with third-party libs to a minimum. I don't mind linking out to Ramda as a tool that can be used, but its implementation could change at any time and this adds to the maintenance overhead of our own docs. 

If you could update this PR to remove everything except for the link to the package, I'll be happy to merge.

2022-05-01 16:29 UTC, alireza-bonab commented
Since there is already a solution on using the `query-string` package, I thought it would be helpful to add another solution using `ramda` this time.

2022-05-02 11:41 UTC, chaance requested changes
Requested changes. Thanks again!

2022-05-02 11:41 UTC, chaance commented on docs/pages/faq.md
> +### Other solutions
```suggestion
```

Remove lib-specific docs

2022-05-10 22:06 UTC, chaance requested changes

2022-05-10 22:06 UTC, chaance commented on docs/pages/faq.md
> +### Structured data using [`query-string`][query-string]
```suggestion
```

2022-05-10 22:07 UTC, chaance approved these changes

2022-05-10 22:07 UTC, merged