feat(node): add remove() and getFilePath() methods to `NodeOnDiskFile`
remix-run/remix pull request #3034
Opened 2022-04-30 09:38 UTC by cstrnt

Closes: #3021

- [ ] Docs
- [x] Tests

Testing Strategy:

- Added a `test` script in the `remix-node` package
- Added a simple unit test for the `createFileUploadHandler` function

2022-07-06 09:48 UTC, cstrnt commented
@kentcdodds @ryanflorence @mjackson any chance you could take a look at this at some time?

2022-07-06 09:51 UTC, machour commented
@cstrnt can you fix conflicts? That would help for the review

2022-07-06 11:29 UTC, cstrnt commented
@machour sure thing, PR sat around for some time lol

2022-07-06 17:51 UTC, MichaelDeBoey requested changes

2022-07-06 17:51 UTC, MichaelDeBoey commented on packages/remix-node/__tests__/parseMultipartFormData-test.ts
> +} from "../upload/fileUploadHandler";
```suggestion
import type { NodeOnDiskFile } from "../upload/fileUploadHandler";
import { createFileUploadHandler } from "../upload/fileUploadHandler";
```

2022-07-06 17:51 UTC, MichaelDeBoey commented on packages/remix-node/package.json
> +  },
We have this already in the root of the project

```suggestion
```

2022-07-07 10:28 UTC, MichaelDeBoey commented
@cstrnt It seems like something went wrong when rebasing.

2022-07-07 17:07 UTC, MichaelDeBoey approved these changes

2022-07-08 06:33 UTC, cstrnt commented
The one failing test doesn't correlate to my code at all. Is it known to be a flaky one?

2022-07-08 16:56 UTC, kentcdodds commented
Can you help me understand what the use case for this change is?

2022-07-08 23:17 UTC, machour commented
@kentcdodds from the related issue #3021 

> I'm currently fiddling around with Remix and while using unstable_createFileUploadHandler I've noticed that the filePath property on a NodeOnDiskFile is private. I don't think that this is really useful because I want to do some cleanup after using the file.
>
> If it's better to keep the filePath property private, I think it would be nice to add a function called remove or cleanup that unlinks the file in the filesystem.

2022-07-08 23:27 UTC, kentcdodds commented
Got it. I'll put this on @mjackson's plate 👍

2022-08-04 06:21 UTC, cstrnt commented
@kentcdodds @mjackson small reminder 🤔

2022-08-04 21:43 UTC, kentcdodds commented
Sorry, we've been very busy with other priorities. We'll get to this eventually. Thank you for your patience.

2022-08-10 19:24 UTC, cstrnt commented
I’m deeply sorry, but I don’t feel like supporting a project led by such toxic lead maintainers

2022-08-10 19:24 UTC, closed without merging