chore(remix-dev): add support for importing `*.webmanifest` files
remix-run/remix pull request #3081
Opened 2022-05-03 19:11 UTC by mcansh

webmanifest files are *just* json files with a different name https://developer.mozilla.org/en-US/docs/Web/Manifest

I'll add a test momentarily

closes #2954

2022-05-04 12:45 UTC, MichaelDeBoey approved these changes

2022-05-04 22:42 UTC, bewildergeist requested changes
The OP in #2954 is actually requesting to import `*.webmanifest` files as static fingerprinted assets, not as JSON.

2022-05-04 22:42 UTC, bewildergeist commented on packages/remix-dev/compiler/loaders.ts
> +  ".webmanifest": "json",
Hold up — this should import as a `"file"` instead in order to solve the use case requested in #2954 — see my comment here: https://github.com/remix-run/remix/issues/2954#issuecomment-1117999207

2022-05-05 00:26 UTC, mjackson approved these changes

2022-05-05 19:28 UTC, MichaelDeBoey approved these changes

2022-05-10 20:10 UTC, merged