chore(remix-server-runtime): warn against using `expires` in `createCookieSessionStorageFactory` and `createSessionStorageFactory`
remix-run/remix pull request #3091
Opened 2022-05-04 17:35 UTC by mcansh

specifying an 'expires' will cause all uses of `commitSession` to use that date

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [x] Tests

Testing Strategy:

This test covers this code: https://github.com/remix-run/remix/blob/29cf8ff5288d97405e09812dfc8f30efa10bb1d2/packages/remix-server-runtime/__tests__/sessions-test.ts#L142

2022-05-04 22:15 UTC, MichaelDeBoey approved these changes

2022-05-04 23:19 UTC, mjackson requested changes
Let's also warn when using `createCookie`. I can't think of any reason you'd want to create a cookie right off the bat with an `expires` value.

2022-05-04 23:19 UTC, mjackson commented on packages/remix-server-runtime/sessions.ts
> +      `Instead use the second argument to commitSession \`commitSession(session, { expires })\` to set the expires value.`
```suggestion
      `Instead, use \`commitSession(session, { expires })\` to set the expires value.`
```

2022-05-05 16:50 UTC, mcansh commented
adding a test for the warning for "missing secrets" while im in here, and looks like the sessionStorages call out to createCookie so we end up with 2 warnings, moving the linear issue back to `in development` and reassigning it while i look into that 😬

2022-05-06 00:42 UTC, MichaelDeBoey requested changes

2022-05-06 00:42 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +    !(expires instanceof Date),
It would lower the cognitive load if we just check if `expires` is set

```suggestion
    !expires,
```

2022-05-18 04:09 UTC, mjackson commented on packages/remix-server-runtime/cookies.ts
> +      `or \`serialize("value", { expires })\` if you're creating a cookie yourself.`
```suggestion
      `You can use \`commitSession(session, { expires })\` if using a session storage object, ` +
      `or \`cookie.serialize("value", { expires })\` if you're using the cookie directly.`
```

2022-05-18 04:20 UTC, mjackson approved these changes

2022-05-18 19:13 UTC, merged