feat(remix-dev): clean up which button clicked submit implementation
remix-run/remix pull request #3094
Opened 2022-05-04 20:46 UTC by mcansh

Signed-off-by: Logan McAnsh <logan@mcan.sh>

2022-05-04 22:55 UTC, mjackson requested changes
Let's also remove the unused `useComposedRefs` function in this file.

2022-05-04 22:55 UTC, mjackson commented on packages/remix-react/components.tsx
> +        console.log(Object.fromEntries(formData));
Remove

2022-05-04 22:55 UTC, mjackson commented on packages/remix-react/components.tsx
> +                  | HTMLInputElement
Let's create a separate type for this and use it here.

```ts
type HTMLFormSubmitter = HTMLButtonElement | HTMLInputElement;
```

2022-05-04 22:58 UTC, mcansh commented on packages/remix-react/components.tsx
> +        console.log(Object.fromEntries(formData));
weird, i thought i did!

2022-05-05 00:24 UTC, mjackson approved these changes

2022-05-05 00:25 UTC, merged