docs(example): add twind example
remix-run/remix pull request #3119
Opened 2022-05-07 07:29 UTC by nexxeln

This example shows how to use [Twind](https://twind.dev) with Remix. 
Thank you. Remix rocks!

2022-05-09 22:23 UTC, kentcdodds requested changes
Sweet! Thanks! Does this server render? It doesn't look like it does. Is it possible to make it so we don't get a flash of unstyled content before the JS loads?

2022-05-10 02:40 UTC, nexxeln commented
Twind does support server side rendering: 
- https://twind.dev/usage-guides/ssr.html

I'll implement this in a bit.

2022-05-10 04:26 UTC, nexxeln commented
Turns out, for SSR in Remix they have a package. I'll use that and commit the changes.

2022-05-10 09:07 UTC, MichaelDeBoey requested changes

2022-05-10 09:07 UTC, MichaelDeBoey commented on examples/twind/app/root.tsx
> +        {process.env.NODE_ENV === 'development' && <LiveReload />}
```suggestion
        <LiveReload />
```

2022-05-10 21:12 UTC, kentcdodds approved these changes
Sweet! Thanks!

2022-05-10 21:12 UTC, merged