Add optional type safety to cookies
remix-run/remix pull request #3224
Opened 2022-05-18 16:34 UTC by mikeybinnswebdesign

- [ ] Docs
- [ ] Tests

Testing Strategy:

I'm not really sure about how to automate testing this because it only adds an optional type. `npm run lint` and `yarn test` run with no issues with my code. I don't see a way to run a specific type check.

I can use Typescript Intellisense in VS Code to see that the type is correctly applied when it is specified using the generic parameter for createCookie and the type is set to any when it is not (current behaviour).

e.g.
```ts
let cookie = createCookie(); 
let variable = cookie.parse(); // variable type = any. Current behaviour. 
```
```ts
let cookie = createCookie<string>(); 
let variable = cookie.parse(); // variable type = string
```
```ts
let cookie = createCookie<{some_value: string}>(); 
let variable = cookie.parse(); // variable type = {some_value: string}
```

fix note:
Adding type safety to the serialise function produced an error in the function. 
`This condition will always return 'false' since the types 'Type' and 'string' have no overlap.`
I fixed it by adding a type assertion to the value to make it read as "any". I don't know why the error occurred, to me it looks like a shortcoming with Typescript rather than an actual bug, but I think this should be double checked.

2022-05-19 12:07 UTC, MichaelDeBoey requested changes

2022-05-19 12:07 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +  serialize(value: Type, options?: CookieSerializeOptions): Promise<string>;
Probably a good idea to rename `Type` to `Value`

```suggestion
  serialize(value: Value, options?: CookieSerializeOptions): Promise<string>;
```

2022-05-19 12:07 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +  ): Promise<Type | null>;
```suggestion
  ): Promise<Value | null>;
```

2022-05-19 12:07 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +export interface Cookie<Type = any> {
```suggestion
export interface Cookie<Value = any> {
```

2022-05-19 12:07 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +export type CreateCookieFunction = <Type = any>(
```suggestion
export type CreateCookieFunction = <Value = any>(
```

2022-05-19 12:07 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +) => Cookie<Type>;
```suggestion
) => Cookie<Value>;
```

2022-05-19 12:41 UTC, MichaelDeBoey requested changes

2022-05-19 12:41 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +            : await encodeCookieValue(sign, value, secrets),
This can be reverted

```suggestion
          value === "" ? "" : await encodeCookieValue(sign, value, secrets),
```

2022-05-19 12:41 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +export interface Cookie<Value = any> {
In this case it doesn't really matter, but it's a good practice to say what type it should extend.

```suggestion
export interface Cookie<Value extends any = any> {
```

2022-05-19 12:46 UTC, mikeybinnswebdesign commented
@MichaelDeBoey I don't know if I need to request a review after I resolve these changes or if you get notified anyway, let me know if it's spamming you and I'll stop 👍

2022-05-19 12:48 UTC, MichaelDeBoey requested changes

2022-05-19 12:48 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +export type CreateCookieFunction = <Value extends any = any>(
```suggestion
export type CreateCookieFunction = <Value extends unknown = unknown>(
```

2022-05-19 12:50 UTC, MichaelDeBoey approved these changes

2022-05-19 13:53 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +            : await encodeCookieValue(sign, value, secrets),
This is not the problem now

2022-05-19 14:03 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +            : await encodeCookieValue(sign, value, secrets),
The problem is within `sessions.ts` now
https://github.com/remix-run/remix/runs/6507483095?check_suite_focus=true#step:6:125

2022-05-19 14:09 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +export interface Cookie<Value extends unknown = unknown> {
Let's keep `any` (for now), as it's causing some other type errors, which would bring us really far on this.
https://github.com/remix-run/remix/runs/6507483095?check_suite_focus=true#step:6:125

```suggestion
export interface Cookie<Value extends any = any> {
```

2022-05-19 14:15 UTC, MichaelDeBoey approved these changes

2022-05-26 10:40 UTC, mikeybinnswebdesign commented
@MichaelDeBoey Should the serialise function also allow null? This way, you can serialise null as a form of deleting the cookie, because parsing the cookie would return null, same as if it didn't exist.
I don't know if there's a better way to handle clearing / deleting a specific cookie. there's no Delete-Cookie header to do so. I can only think of setting an expires that's in the past, but that's not exactly clean.

2022-05-26 12:12 UTC, MichaelDeBoey requested changes

2022-05-26 12:12 UTC, MichaelDeBoey commented on packages/remix-server-runtime/cookies.ts
> +  ): Promise<string>;
@mikeybinnswebdesign As explained in https://stackoverflow.com/a/53573622/4001231, setting the cookie with an expired date in the past is the way [the spec](https://tools.ietf.org/search/rfc6265) defines how you should delete a cookie.

> Finally, to remove a cookie, the server returns a Set-Cookie header with an expiration date in the past.  The server will be successful in removing the cookie only if the Path and the Domain attribute in the Set-Cookie header match the values used when the cookie was created.

```suggestion
  serialize(value: Value, options?: CookieSerializeOptions): Promise<string>;
```

2022-06-21 15:12 UTC, mikeybinnswebdesign commented
Sorry @MichaelDeBoey I missed your response to this, all makes sense 😄

2022-07-24 17:25 UTC, mikeybinnswebdesign commented
@MichaelDeBoey I have done the work to make sessions work with a default value of unknown. Am I okay to rebase the patch-5 branch onto the dev branch and then commit those changes?

2023-01-15 15:09 UTC, mikeybinns commented
@sergiodxa has raised a good point in [this discussion](https://github.com/remix-run/remix/discussions/5100#discussioncomment-4688549) that cookies are user input and therefore could be different from what we expect. This shouldn't be a problem with encrypted cookies, so I'm going to update this PR to only type the cookie if a secret value is set.

2023-01-22 23:25 UTC, mikeybinns commented
I've tried to do this over the weekend but I'm not able to work out how to do it because the function is returned by the factory function, rather than being its own named function. Perhaps someone with more Typescript knowledge may have better luck?

2023-01-24 14:43 UTC, chaance commented
`createCookie<string>()` isn't really type-safe, it's basically just a fake promise in this case. Even with encrypted cookies, you still want to validate the input somewhere on your server.

My suggestion is to create a wrapper for `createCookie` that handles runtime validation for you. And if you *really* want to skip runtime validation you're free to do so, I just don't think we want to encourage that behavior!

```ts
import {
  createCookie as remixCreateCookie,
  type CookieOptions,
  type CookieParseOptions,
} from "@remix-run/node";

interface ValidatedCookieValue {
  whatever: string;
}

export function createCookie(
  name: string,
  cookieOptions?: CookieOptions
) {
  let cookie = remixCreateCookie(name, cookieOptions);
  return {
    ...cookie,
    async parse(
      cookieHeader: string | null,
      parseOptions?: CookieParseOptions
    ): Promise<ValidatedCookieValue> {
      let parsed = await cookie.parse(cookieHeader, parseOptions);
      assertValidCookieValue(parsed);
      return parsed;
    },
  };
}
```

This could also be done in a more flexible way, say if `parse` was generic and accepted its own validation function through which you could infer the return type. But you should be able to achieve what you're after as long as you're validating input.

2023-01-24 14:43 UTC, closed without merging

2023-01-24 14:53 UTC, mikeybinns commented
Okay, thanks @chaance, @sergiodxa echoed the same concerns and you're both right, we should be validating this cookie and not relying on false types 👍

2024-02-18 15:26 UTC, ansavchenco commented
Maybe i'm missing something but can the result of `cookie.parse` be anything other than `string` (or `null`/`undefined`) if cookie is not there? Why generic or `any`?