Docs: update links to new react-router docs
remix-run/remix pull request #3253
Opened 2022-05-19 15:13 UTC by JNaftali

"Other api" docs about React Router were pointing at the old urls (which do not redirect properly). Updated to point to the new ones

2022-05-19 16:45 UTC, machour commented
@jacob-ebey is there something that needs fixing on the website for redirections? If not, please merge this one 🙏🏼

2022-05-19 16:59 UTC, MichaelDeBoey requested changes

2022-05-19 16:59 UTC, MichaelDeBoey commented on docs/other-api/react-router.md
> +- [`useResolvedPath`](https://reactrouter.com/docs/en/v6/hooks/use-resolved-path)
Omitting locale + version number will always point to latest version

```suggestion
- [`Outlet`](https://reactrouter.com/docs/components/outlet)
- [`useLocation`](https://reactrouter.com/docs/hooks/use-location)
- [`useNavigate`](https://reactrouter.com/docs/hooks/use-navigate)
- [`useParams`](https://reactrouter.com/docs/hooks/use-params)
- [`useResolvedPath`](https://reactrouter.com/docs/hooks/use-resolved-path)
```

2022-05-20 09:55 UTC, MichaelDeBoey approved these changes

2022-05-20 09:55 UTC, merged