Added .node support in the compiler and docs for the feature
remix-run/remix pull request #3263
Opened 2022-05-19 19:23 UTC by benwis

## Changes Made
This pull requests adds an esbuild plugin and some tweaks to the Remix compiler to allow the import of `.node` files in Remix's loaders and actions. While I was motivated by the desire to write Rust helper functions for server side modules, this was also mentioned in this [other pull request](https://github.com/remix-run/remix/pull/703) for .node imports for remix-tailwind, and in [a discussion](https://github.com/remix-run/remix/discussions/2560) by @nicksrandall for sharp support.

I have started [a discussion](https://github.com/remix-run/remix/discussions/3201) here, but as of now hasn't generated much traffic.

## Benefits
The primary benefit I see is the ability to run other language's code on your server easily in Remix. This could be done in Rust using napi-rs, in Python, or in C. That offers substantial benefits in performance, opens possibilities for easy concurrency, and other possibilities.

## Limitations
One of the biggest limitations is that it can only run on Node based platforms. Napi-rs is currently working on Deno support, so we may see this come there as well. 

## Testing
I have modified the Rust example in the main repo with to generate a sum() function with [napi-rs](https://napi.rs/) and use that to perform the addition that example does. The repo for this is [here](https://github.com/benwis/rust-remix). There are a few build steps as described in that README that must be performed, depending on the platform you're running Remix on.

- [x] Docs

2022-05-19 19:37 UTC, benwis commented
That was harder than I expected to get git to agree. Thanks @MichaelDeBoey!

2022-05-19 20:15 UTC, MichaelDeBoey requested changes

2022-05-19 20:15 UTC, MichaelDeBoey commented on docs/guides/native-node-modules.md
> +# #Limitations
```suggestion
## Limitations
```

2022-06-29 16:30 UTC, jacob-ebey requested changes

2022-06-29 16:30 UTC, jacob-ebey commented on packages/remix-dev/compiler.ts
> +      let parentFolderPath = file.path.slice(0, file.path.lastIndexOf("/"))
please use `path.dirname()` instead of split. This will break on windows machines.

2022-06-29 16:30 UTC, jacob-ebey commented on packages/remix-dev/compiler/plugins/nativeNodeModules.ts
> +        try { module.exports = require(absolutePath) }
This will break node ESM. Is it possible to load via `import` statements?

2022-06-29 16:30 UTC, jacob-ebey commented on packages/remix-dev/compiler/plugins/nativeNodeModules.ts
> +                path: require.resolve(args.path, { paths: [args.resolveDir] }),
Add `sideEffects: false` here to make sure this can be optimized out of client bundles.

2022-07-18 15:34 UTC, closed without merging