fix(remix-dev): multiple nested pathless layout routes
remix-run/remix pull request #3331
Opened 2022-05-30 02:41 UTC by pokedotdev

Closes: #3327

- [ ] Docs
- [x] Tests

2022-05-30 14:32 UTC, MichaelDeBoey requested changes

2022-05-30 14:32 UTC, MichaelDeBoey commented on packages/remix-dev/config/routesConvention.ts
> +      else if (isLayoutRoute) uniqueRouteId += lastSegment;
Let's make this less error-prone

```suggestion
      if (isIndexRoute) {
        uniqueRouteId += "?index";
      } else if (isLayoutRoute) {
        uniqueRouteId += lastSegment;
      }
```

2022-09-24 15:49 UTC, apalumbo commented
@MichaelDeBoey is this PR still to approve?

2022-11-22 14:17 UTC, brophdawg11 commented
Oh interesting, I didn't know we had a separate PR for this. This is also fixed by #4421 which was initially addressing #3014 but uncovered this same issue during testing.  I think I lean towards the solution in #4421 since rather than mess with the `id` just to make it unique, we skip the check entirely for pathless layout routes which, by definition, create the potential for path collisions.  I'll check with the team as well and we'll get one of these merged to fix #3327.  

It may make sense to keep the integration tests from this PR even if we go with #4421 - I'll take a closer look and make sure we're properly covered.

2022-11-28 05:24 UTC, Vivalldi reviewed
Noticed a small thing regarding the `slug index & foo layout` test

2022-11-28 05:24 UTC, Vivalldi commented on integration/multiple-pathless-routes-test.ts
> +  expect(text).toMatch(TEXTS.SLUG_LAYOUT);
```suggestion
  expect(text).toMatch(TEXTS.SLUG_CHILD);
```

2023-01-24 13:52 UTC, chaance commented
This got a bit outdated -- very sorry it took us a bit to follow up. As @brophdawg11 mentioned this should have been taken care of already, and most of the logic has been moved to React Router. If there is still an issue I'd suggest opening one in that repo so we can give it a fresh look.

2023-01-24 13:52 UTC, closed without merging