chore(refactor): Create `magicExports` in Rollup build
remix-run/remix pull request #3543
Opened 2022-06-22 20:59 UTC by chaance

This PR removes all `magicExports` modules from the source code and emits the files via Rollup instead. This eliminates any issues with TS or Node module resolution that will occur from copying the build output into a `dist` directory alongside the package source. 

This will unblock https://github.com/remix-run/remix/pull/3540 which in turn will unblock the work needed to implement Changesets.

2022-06-22 21:18 UTC, MichaelDeBoey requested changes

2022-06-22 21:18 UTC, MichaelDeBoey commented on package.json
> +    "lodash": "^4.17.21",
Could we use `lodash.camelcase` instead?

https://www.npmjs.com/package/lodash.camelcase

```suggestion
    "lodash.camelcase": "^4.3.0",
```

2022-06-22 21:18 UTC, MichaelDeBoey commented on package.json
> +    "@types/lodash": "^4.14.182",
```suggestion
    "@types/lodash.camelcase": "^4.3.7",
```

2022-06-22 21:18 UTC, MichaelDeBoey commented on rollup.config.js
> +import camelCase from "lodash/camelCase";
```suggestion
import camelCase from "lodash.camelcase";
```

2022-06-22 21:18 UTC, MichaelDeBoey commented on rollup.config.js
> +        },
These looks like a left-over from a copy/paste?

https://github.com/remix-run/remix/blob/e85757e84cf7e83cf754681917cf4bcce717e544/packages/remix-architect/magicExports/remix.ts#L1-L5

```suggestion
```

2022-06-22 21:18 UTC, MichaelDeBoey commented on rollup.config.js
> +      break;
I don't think this one is necessary, because we already have this exported by `@remix-run/cloudflare`

```suggestion
```

2022-06-22 21:18 UTC, MichaelDeBoey commented on rollup.config.js
> +      break;
Same

```suggestion
```

2022-06-22 21:19 UTC, MichaelDeBoey commented on package.json
> +    "lodash": "^4.17.21",
Oops you were faster than I was reviewing 🙈

2022-06-22 21:28 UTC, brophdawg11 commented
The only thing I notice on a quick diff of a dev `build/` versus here is these 2 lines are missing at the top of the generated files in this branch.  We don't need `use strict` - but unsure if the `__esModule` is relevant for anything in the bundle landscape or just rollup cruft though

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });
```

2022-06-22 21:30 UTC, brophdawg11 approved these changes

2022-06-22 22:46 UTC, MichaelDeBoey requested changes

2022-06-22 22:59 UTC, chaance commented on rollup.config.js
> +      };
I'm going to leave these as-is, but we can revisit in a follow-up PR if needed. The goal here is to change the config but leave the published output alone.

2022-06-22 23:10 UTC, merged

2022-06-23 08:02 UTC, MichaelDeBoey commented on rollup.config.js
> +      };
I created https://github.com/remix-run/remix/pull/3546 as a follow-up