chore(integration): improve build failure output in tests
remix-run/remix pull request #3567
Opened 2022-06-24 21:02 UTC by jenseng

Display the actual contents of stderr when things fail. I preserved the commented-out debug stuff, as that can be useful for seeing what's happening when things **don't** fail.

Testing Strategy:
 * Ran all integration tests, they passed, and no output changed
 * Made a test fail and confirmed I saw the new error message and useful output :)

2022-06-24 21:21 UTC, MichaelDeBoey requested changes
LGTM!

One small thing: be sure to remove the `chalk` import from the file

2022-06-24 21:25 UTC, jenseng commented
✅  Done!

2022-06-24 21:27 UTC, MichaelDeBoey approved these changes

2022-06-25 06:34 UTC, kentcdodds approved these changes
Thanks!

2022-06-25 06:34 UTC, merged