chore(remix-dev): improve compiler with lodash
remix-run/remix pull request #3597
Opened 2022-06-28 23:34 UTC by gervasiocaj

Improves usage of the lodash library on the remix-dev compiler.
I believe we can start applying some functional programming ideas to improve the testability of this package. Please comment if there are some ongoing efforts on this.
Tested this with the following script:

```sh
# yarn
# npx playwright install
yarn test:primary --selectProjects dev
yarn test:integration
```

2022-06-29 07:59 UTC, machour commented
Hi @gervasiocaj and thank you for this PR. 
Can you please sign the CLA by adding your name to the contributors?

2022-07-14 08:06 UTC, MichaelDeBoey commented
@gervasiocaj Can you please explain a bit why this change would be beneficial?

This seems just like a personal preference to me & I don't think we should merge this PR then.
Otherwise we could have PRs that keep moving this back & forth.

2022-07-14 13:43 UTC, machour commented on packages/remix-dev/package.json
> +    "meow": "^7.1.1",
This change doesn't look right

2022-07-18 14:51 UTC, gervasiocaj commented on packages/remix-dev/package.json
> +    "meow": "^7.1.1",
Yes, this was a mishap

```suggestion
```

2022-07-18 15:51 UTC, gervasiocaj commented
@MichaelDeBoey the main issue at first was the `ImportsCache` implementation, which was not clear enough to me. Since `lodash `was already a dependency and had a tested implementation of `memoize`, my reasoning was to use it.

I also took the liberty of removing the `lodash.debounce` dependency as it is duplicate code, and changing the function call to the more readable FP style instead of having the trailing delay argument.

As for performance, I considered [this article](https://bretcameron.medium.com/how-javascript-maps-can-make-your-code-faster-90f56bf61d9d) as a reference, but as of now, [this response](https://stackoverflow.com/a/49164774/2282532) and yours made me realize that I have to consider the nature of the keys (pathnames) and how impactful it will be.

Please let me know what you think, and thank you for the feedback so far.

2022-07-18 16:28 UTC, MichaelDeBoey requested changes
@gervasiocaj I'm in favor of removing the `@types/lodash.debounce` & `lodash.debounce` dependencies.
I do however think we should keep the normal `lodash` functions instead of the FP functions.

I also think we should keep the implementation of `optimizeRoutes` & `optimizeRouteImports` as close to the original as possible

2022-07-18 16:28 UTC, MichaelDeBoey commented on packages/remix-dev/compiler/assets.ts
> +      parentImports = parentImports.concat(optimized);
Let's keep this as it was
```suggestion
      parentImports = parentImports.concat(
        optimizeRouteImports(route.parentId, routes, parentImports)
      );
```

2022-07-18 16:28 UTC, MichaelDeBoey commented on packages/remix-dev/compiler/assets.ts
> +    let routeImports = (route.imports || []).filter(urlMissingInParentImports);
Same
```suggestion
    let routeImports = (route.imports || []).filter(
      (url) => !parentImports.includes(url)
    );
```

2022-07-18 16:28 UTC, MichaelDeBoey commented on packages/remix-dev/compiler/assets.ts
> +  let optimizeRouteImports = memoize(function (
Let's keep this function outside of `optimizeRoutes`

2022-07-18 20:07 UTC, kentcdodds reviewed
Thanks for this contribution, but I think we're happy with how it is. It's nice and simple as-is. Thanks anyway.

2022-07-18 20:07 UTC, closed without merging