docs: add basic doc entry for how nightly releases work and how they run
remix-run/remix pull request #3836
Opened 2022-07-25 20:50 UTC by mcansh

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2022-07-25 22:51 UTC, MichaelDeBoey requested changes

2022-07-25 22:51 UTC, MichaelDeBoey commented on docs/pages/contributing.md
> +Nightly releases will run the action files from the `main` branch as scheduled workflows will always use the latest commit to the default branch, signified by [this comment on the nightly action file
```suggestion
Nightly releases will run the action files from the `main` branch as scheduled workflows will always use the latest commit to the default branch, signified by [this comment on the nightly action file][nightly-action-comment] and the explicit branch appended to the reuasable workflows in the [postrelease action][postrelease-action], however they clone the `dev` branch during their set up as that's where we want our nightly releases to be cut from. From there, we check if the git sha is the same and only cut a new nightly if something has changed.
```

2022-07-28 20:08 UTC, kentcdodds approved these changes
This is great and highlights how awesome the work you've done is @mcansh. Amazing work 👍

2022-07-28 20:08 UTC, kentcdodds commented
Is there a reason this is still a draft PR?

2022-07-28 20:10 UTC, mcansh commented
> 

no reason other than i forgot to move when i updated linear 😆

2022-07-28 22:33 UTC, merged