chore(docs): Hide TOC in pages where only the title is displayed
remix-run/remix pull request #3843
Opened 2022-07-26 22:46 UTC by davidblnc

This PR aims to remove the table of contents in the docs where it's not necessary (example provided as screenshot).

![imagen](https://user-images.githubusercontent.com/40642621/181124887-e0a76b4c-ffe7-48e8-b029-e1ceeee2d215.png)

2022-07-27 01:53 UTC, mcansh commented
thanks! i’m wondering if it’s better to have this automated in our markdown parser. @ryanflorence

2023-01-24 08:14 UTC, machour requested changes
@davidblnc can you rebase this on top of main?
Seems like we do need a toc for browser support now, otherwise it looks ok for merge.

2023-01-24 09:29 UTC, MichaelDeBoey requested changes

2023-01-24 09:29 UTC, MichaelDeBoey commented on docs/guides/browser-support.md
> +toc: false
Even though it's a small page, we have multiple headers on this page

```suggestion
```

2023-01-25 13:16 UTC, machour commented
Superseded by #5249, thank you nonetheless @davidblnc  🙏🏼

2023-01-25 13:16 UTC, closed without merging