docs: fix a typo in jokeId param
remix-run/remix pull request #3962
Opened 2022-08-08 09:50 UTC by shairez

Closes: #

- [x] Docs
- [ ] Tests

The `:jokeId` and `$jokeId` convention is confusing. 

The tutorial shows `/jokes/:jokeId` but then talks about `$jokeId` referring to what we just saw.
It looks like a typo

2022-08-08 10:18 UTC, MichaelDeBoey requested changes

2022-08-08 10:18 UTC, MichaelDeBoey commented on docs/tutorials/jokes.md
>  `/jokes/:jokeId`
This should be

```suggestion
`/jokes/$jokeId`
```

2022-08-08 10:18 UTC, MichaelDeBoey commented on docs/tutorials/jokes.md
> +Here the parameter `:jokeId` can be anything, and we can lookup that part of the URL up in the database to display the right joke. To make a parameterized route, we use the `$` character in the filen
```suggestion
Here the parameter `$jokeId` can be anything, and we can lookup that part of the URL up in the database to display the right joke. To make a parameterized route, we use the `$` character in the filename. ([Read more about the convention here][the-route-filename-convention]).
```

2022-08-08 10:18 UTC, MichaelDeBoey commented
@shairez Please sign the CLA in order to get this merged.

2022-08-30 06:56 UTC, shairez commented
@MichaelDeBoey  took me a while, but now it's done :)

2022-08-30 06:59 UTC, merged

2022-08-30 06:59 UTC, machour commented
Thank you @shairez !