Fix link
remix-run/remix pull request #3965
Opened 2022-08-08 21:42 UTC by protofarer

Link to Remix App Server page broken, just remove md extension.

2022-08-08 22:14 UTC, MichaelDeBoey requested changes

2022-08-08 22:14 UTC, MichaelDeBoey commented on docs/other-api/dev.md
> +[remix-app-server]: serve
```suggestion
[remix-app-server]: /other-api/serve
```

2022-08-08 22:14 UTC, MichaelDeBoey commented
@protofarer Please sign the CLA in order to get this merged

2022-09-17 18:41 UTC, machour commented
It seems that this have been fixed by another PR, thank you anyway!

2022-09-17 18:41 UTC, closed without merging