Use copySync in playground:new to avoid race condition errors when generating new playgrounds
remix-run/remix pull request #4001
Opened 2022-08-15 17:14 UTC by n8agrin

`yarn playground:new` was generating random errors related to unlinking/deleting files that did not exist. File copying was using an asynchronous method to move files into playground directories.

This change makes the copy/move operation synchronous and eliminates race conditions, ensuring `yarn playground:new` always succeeds.

2022-08-15 17:20 UTC, MichaelDeBoey requested changes
I don't think this changes anything tbh, as we're awaiting for the sync to be finished before we continue (just like we would use the synchronous function) 🤔

2022-08-15 17:20 UTC, MichaelDeBoey commented on rollup.utils.js
> +          await fse.copySync(writtenDir, destDir);
No need for `await` anymore
```suggestion
          fse.copySync(writtenDir, destDir);
```

2022-08-15 17:28 UTC, n8agrin commented on rollup.utils.js
> +          await fse.copySync(writtenDir, destDir);
Good call.

2022-08-15 17:30 UTC, n8agrin commented
@MichaelDeBoey regarding this not changing anything, a trivial repro is to checkout a new clone of remix and run `yarn playground:new`. On my machine that frequently produces errors like the following:

```
packages/remix-dev/server-build.ts → build/node_modules/@remix-run/dev, build/node_modules/@remix-run/dev/dist...
[!] (plugin copy-to-remix-playground) Error: ENOENT: no such file or directory, unlink '/Users/nate/Projects/remix-two/playground/playground-1660456168247/node_modules/@remix-run/dev/dist/cli/migrate/migrations/replace-remix-imports/transform/index.js'
Error: ENOENT: no such file or directory, unlink '/Users/nate/Projects/remix-two/playground/playground-1660456168247/node_modules/@remix-run/dev/dist/cli/migrate/migrations/replace-remix-imports/transform/index.js'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: yarn rollup -c
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at createNewProject (/Users/nate/Projects/remix-two/scripts/playground/new.js:46:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9794,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I agree that in theory the `await fse.copy` gesture should prevent this, and I didn't dig into the internals of `fse`, but changing `copy` to `copySync` completely eliminates the issue for me.

2022-08-15 18:33 UTC, jacob-ebey commented
@MichaelDeBoey I said to put this PR up. It's something I've ran into locally quite a bit and I address it with the above solution. I'm honestly not sure why async ops are breaking here, but they are.

2022-08-17 00:23 UTC, MichaelDeBoey approved these changes

2022-08-17 17:08 UTC, kentcdodds approved these changes
Seems fine 👍

2022-08-17 17:09 UTC, kentcdodds commented
Just sitting like this forever. Even after a refresh 🤦‍♂️

![Uploading image.png…]()

2022-08-17 17:43 UTC, merged