chore(templates):  change`&&` into `npm-run-all`
remix-run/remix pull request #4016
Opened 2022-08-18 08:00 UTC by wxh06

- [x] Templates

Change `remix build && run-p "dev:*"` into `npm-run-all build -p "dev:*"`.
As a result, it's no longer necessary to edit multiple `scripts` in `package.json` when modifying `build` script.

For example, adding `rsync` to copy fonts required by CSS `@font-face`. See https://github.com/remix-run/remix/issues/1153#issuecomment-1056989834

```json
{
  "scripts": {
    "build": "remix build && rsync -r node_modules/bootstrap-icons/font/fonts public/build/_assets",
    "dev": "npm-run-all build -p \"dev:*\"",
  }
}
```

Reference: https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#run-a-mix-of-sequential-and-parallel-scripts

2022-09-04 23:47 UTC, machour approved these changes

2023-02-09 13:18 UTC, chaance commented
@wxh06 Mind resolving conflicts so I can get this merged?

2023-02-11 20:41 UTC, MichaelDeBoey requested changes
Maybe we should make the parallel part a bit more explicit now? 🤔

2023-02-11 20:41 UTC, MichaelDeBoey commented on templates/arc/package.json
> +    "dev": "npm-run-all build -p \"dev:*\"",
```suggestion
    "dev": "npm-run-all build --parallel \"dev:*\"",
```

2023-02-11 20:41 UTC, MichaelDeBoey commented on templates/cloudflare-pages/package.json
> +    "dev": "npm-run-all build -p \"dev:*\"",
```suggestion
    "dev": "npm-run-all build --parallel \"dev:*\"",
```

2023-02-11 20:41 UTC, MichaelDeBoey commented on templates/cloudflare-workers/package.json
> +    "dev": "npm-run-all build -p \"dev:*\"",
```suggestion
    "dev": "npm-run-all build --parallel \"dev:*\"",
```

2023-02-11 20:41 UTC, MichaelDeBoey commented on templates/deno/package.json
> +    "dev": "npm-run-all build -p \"dev:*\"",
```suggestion
    "dev": "npm-run-all build --parallel \"dev:*\"",
```

2023-02-11 20:41 UTC, MichaelDeBoey commented on templates/express/package.json
> +    "dev": "npm-run-all build -p \"dev:*\"",
```suggestion
    "dev": "npm-run-all build --parallel \"dev:*\"",
```

2023-02-12 01:41 UTC, MichaelDeBoey approved these changes

2023-02-13 22:23 UTC, merged