feat(integration): bring React 18 fixtures in line with `indie-stack` updates
remix-run/remix pull request #4061
Opened 2022-08-24 20:44 UTC by MichaelDeBoey

Follow-up of #4060

2022-08-24 20:45 UTC, MichaelDeBoey commented on integration/helpers/node-template/app/entry.client.tsx
> +}
This isn't really necessary for our integration tests, but I think it's a good idea to keep these consistent with our templates

2022-08-24 20:45 UTC, mcansh commented on package.json
> +    "isbot": "^3.5.1"
all dependencies in the workspace root are "dev dependencies" so we just put them all in "dependencies"

2022-08-24 20:47 UTC, mcansh approved these changes
LGTM, but I'll defer to @jacob-ebey

2022-09-19 17:43 UTC, jacob-ebey requested changes

2022-09-19 17:43 UTC, jacob-ebey commented on integration/helpers/node-template/app/entry.server.tsx
> +  let callbackName = isbot(request.headers.get("user-agent"))
MJ wants these to be two explicit code-paths, something like:
```js
if (isBot) {
  return renderForBot(...);
}

return renderForBrowser(...);
```

2022-10-12 16:34 UTC, merged