feat(dev): use native pnp resolution in esbuild 0.15+
remix-run/remix pull request #4154
Opened 2022-09-07 10:18 UTC by redabacha

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2022-09-29 22:43 UTC, mcansh commented
i was hoping for this PR 🤩 - i know nothing about pnp though, so I'll defer to @pcattori - but if it's good, perhaps we can bump up to 0.15.9 to also include the jsx name collision fixes :)

2022-09-29 22:47 UTC, MichaelDeBoey requested changes

2022-09-29 22:47 UTC, MichaelDeBoey commented on packages/remix-dev/package.json
> +    "esbuild": "0.15.7",
```suggestion
    "esbuild": "0.15.10",
```

2022-09-29 22:48 UTC, MichaelDeBoey commented
@redabacha Could you please rebase your branch onto latest `dev` & resolve conflicts?

2022-09-29 22:57 UTC, redabacha commented on packages/remix-dev/package.json
> +    "esbuild": "0.15.7",
updated :sweat_smile:

2022-09-29 23:28 UTC, pcattori approved these changes

2022-09-29 23:40 UTC, pcattori commented
@mcansh : let's do some solid testing on the `esbuild` upgrade before we merge this

2022-09-29 23:41 UTC, mcansh commented
100%

2022-09-29 23:41 UTC, MichaelDeBoey approved these changes

2022-09-30 17:20 UTC, mattste commented
I just upgraded my team's very small internal app to this P/R and no issues thus far. I'll update if we run into anything.

2022-11-18 22:27 UTC, machour commented
This have been implemented in #4301 
Thank you @redabacha!

2022-11-18 22:27 UTC, closed without merging