feat: update cloudflare-workers template to ESM
remix-run/remix pull request #4198
Opened 2022-09-15 00:10 UTC by jacob-ebey

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2022-09-15 09:49 UTC, MichaelDeBoey requested changes
@jacob-ebey Do we need these updates for the `cloudflare-pages` template as well?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/README.md
> +        uses: styfle/cancel-workflow-action@0.9.1
Latest version is `0.10.0`

```suggestion
        uses: styfle/cancel-workflow-action@0.10.0
```

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/app/entry.server.tsx
> +import { type EntryContext } from "@remix-run/cloudflare";
Let's keep the type at the beginning of the import to keep it consistent with the rest of the codebase

```suggestion
import type { EntryContext } from "@remix-run/cloudflare";
```

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/types/remix-build.d.ts
> +  import { type ServerBuild } from "@remix-run/cloudflare";
```suggestion
  import type { ServerBuild } from "@remix-run/cloudflare";
```

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/package.json
> +    "dev": "npm run build && concurrently \"npm:dev:remix\" \"npm:dev:cloudflare\"",
We're using `npm-run-all` in all other templates/examples, so maybe we should use that here as well to keep it consistent?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/package.json
> -    "@remix-run/cloudflare-workers": "*",
Is it intentional that we're not downloading `@remix-run/cloudflare-workers` by default anymore?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/package.json
> +    "react-dom": "^18.2.0"
Does this mean, we can update the `cloudflare-pages` template to React 18 as well?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/remix.config.js
> -  // publicPath: "/build/",
We keep this commented out for convenience in our other templates, so maybe we should keep them here as well?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/remix.init/index.js
> +  const examplePath = path.resolve(rootDirectory, "wrangler.example.toml");
Is it intentional to keep this file in the root?

We keep `remix.init` files in the same folder in our stacks.

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/remix.init/package.json
> +{
We can just delete this file if we don't have any `dependencies`

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/tsconfig.json
> +  "include": ["**/*.d.ts", "**/*.ts", "**/*.tsx"],
@mcansh Does this have implications for the `convert-to-javascript` migration?

2022-09-15 09:49 UTC, MichaelDeBoey commented on templates/cloudflare-workers/types/remix.env.d.ts
>  /// <reference types="@remix-run/dev" />
Should we move this file to a `types` folder as well in our other templates, so this is consistent?

2022-10-13 11:55 UTC, huw commented
This adds a lot of boilerplate. Has the Remix team considered updating `createEventHandler` or adding a new exported function to `@remix-run/cloudflare-workers`?

2022-10-13 12:03 UTC, MichaelDeBoey commented
@huw Do you mean something like @ekosz is doing in #1207?

2022-10-13 12:12 UTC, huw commented
Yeah, that seems closer to what I’d expect & it feels (very subjectively) more idiomatic.

The reason this PR removes the dependency on `@remix-run/cloudflare-workers` is because it completely supersedes it by inlining the functionality into the template. It would require a few changes to the docs to explain that `@remix-run/cloudflare-workers` is only appropriate for the old service-worker syntax, and that ESM users should copy from this template. My guess is that this isn’t what the Remix team want, unless you’re planning to move away from adapters in the long run?

I suspect it would be easier for end users to understand & upgrade if they only had to make a small change to their `server.js` file—@ekosz’s example is simply:

```js
 import { createEventHandler } from "@remix-run/cloudflare-workers";

 import * as build from "../build";

 const handler = createEventHandler({ build })

 export default {
   fetch(request, env, context) {
     const event = { request, env, waitUntil: context.waitUntil.bind(waitUntil) };
     return handler(event);
   }
 }
 ```

2022-11-21 23:17 UTC, dario-piotrowicz commented
I just wanted to mention that I just pulled down this branch and checked locally on a wrangler project and this PR does seem to work in its current state (compared to #1207 which has a few bits not fully working)

@MichaelDeBoey @jacob-ebey could we get this PR merged soon even if some small things can be improved and iterate over those details afterwards? (so that devs using Cloudflare workers can at least start using the ESM version sooner)

2022-11-22 12:33 UTC, huw commented
@dario-piotrowicz FWIW this is just a change to the Workers template, not any of Remix's actual code. Remix is fully compatible with Workers today, users just need to copy the code in this template into their setups.

However, that requires a pretty specific setup. Users need to be wary of where their `build` is and update the reference in code if they reconfigure Remix, for one. And they have to use Wrangler's built-in bundler, or rebundle the Remix output themselves (since this code does not bundle dependencies into the final server code as-is). It's also using a deprecated config flag in `remix.config.js` to hack around the Remix compiler.

IMHO, as I said above, this is a very brittle approach to solving this problem & doesn't feel in line with the high standards both Remix & Cloudflare tend to aspire to for developer experience. And it would leave significant fragmentation in the Remix DX for users, because the instructions for integrating with ESM vs CJS would end up being very different--much more different than changing between Pages & Workers Sites, which is as simple as updating `remix.config.js` and a handful of lines in the server index file.

Again, the preferable solution would be to update the `@remix-run/cloudflare-workers` package. I gave this a crack today, but because the KV asset handler requires that `__STATIC_CONTENT_MANIFEST` import, getting interop with CJS is much trickier. I think the right approach might be to:

1. Create a new package (`@remix-run/cloudflare-workers-esm` or just `cloudflare-esm`) with ESM-specific code (i.e. tweaked #1207 code).
2. Update the Remix compiler to compile a new `cloudflare-esm` target as ESM with the `neutral` platform, while still bundling browser code.
3. Update the docs.

I really want to stress how unusable this PR would be in its current state & how much additional support load it will create for Cloudflare & Remix. I'm in a busy period rn but would gladly do this properly once I'm through that.

2022-11-22 12:49 UTC, dario-piotrowicz commented
@huw thanks so very much for the nice clarification, yeah I understand that it is only template changes, but this is not at all straightforward to get done without checking out this PR, that's why I was asking to include it so to reduce the barrier to entry (maybe it could be added in a README, docs or something?)

Anyways I had no idea that this was brittle/using a deprecated flag, I thought that the only downside of this solution was the amount of boilerplate needed. Based on what you said I agree that adding something half-baked in at this stage would make things worse rather than better....

Thanks for taking the time to look at this, I'll patiently wait for you to have more time to look into this then 🙂

Also, I don't have much knowledge on how Remix works under the hook, but if you think I could be of any help here please let me know 🙏

2023-02-06 23:50 UTC, MichaelDeBoey commented
@jacob-ebey @huw @dario-piotrowicz I'm wondering if you could obtain the same result with the new config properties that were exposed by #4841 🤔

2023-08-15 23:11 UTC, closed without merging

2023-08-15 23:11 UTC, MichaelDeBoey commented
@jacob-evey Closing this as @pcattori  updated the `cloudflare-workers` template to ESM in #6650