feat(node): add new methods to NodeOnDiskFile class
remix-run/remix pull request #4408
Opened 2022-10-23 00:09 UTC by julienmonnard

Closes: #3021

- [ ] Docs
- [x] Tests

Testing Strategy:

One unit test for each new function, added in the remix-node package.

This is basically the same PR as #3034, but it got closed by its author before being merged. I believe this is a useful feature and would very much like to see it added.

2022-10-24 06:31 UTC, machour approved these changes
Merci Julien for picking up this! 🙌

Just a small update to the changesetand we should be good to go.

2022-10-24 06:31 UTC, machour commented on .changeset/flat-cobras-beam.md
> +Add a "remove" and a "getFilePath" methods to fileUploadHandler
```suggestion
Add "remove" and "getFilePath" methods to fileUploadHandler
```

2022-10-27 00:10 UTC, MichaelDeBoey requested changes

2022-10-27 00:10 UTC, MichaelDeBoey commented on .changeset/flat-cobras-beam.md
> +Add "remove" and "getFilePath" methods to fileUploadHandler
The exported class is called `NodeOnDiskFile`, so I think we should reference that name instead.

```suggestion
Add `getFilePath`& `remove` methods to `NodeOnDiskFile`
```

2022-10-27 09:06 UTC, MichaelDeBoey approved these changes

2022-11-15 11:04 UTC, cstrnt commented
Nice copy pasta :D

2022-11-15 11:24 UTC, julienmonnard commented
Indeed. I'm not trying to hide that fact, it's actually mentioned in the description above.

The main difference with your PR is that this one is still open. I need that feature in my project and would like to see it merged. I was disappointed when you closed yours, and as I cannot reopen a PR, I recreated it.

2022-11-15 14:25 UTC, mcansh approved these changes

2023-01-11 05:51 UTC, julienmonnard commented
Is there something more that should be done for this to be able to make it in one of the next releases?
I guess with the whole react-router/remix stuff happening it was quite tricky, but now that 1.10 wraps it up and has landed, maybe there could be a little slot for this one :)

2023-01-21 16:08 UTC, mcansh approved these changes

2023-01-21 16:35 UTC, merged