fix(remix-react): `Form`'s `method` shouldn't be ignored
remix-run/remix pull request #4413
Opened 2022-10-25 07:33 UTC by maxschwarzmueller

Fixes #4412

2022-10-25 08:56 UTC, machour requested changes
Thank you so much for the reproduction and fix @maxschwarzmueller !
Could you remove the generated file?
I'll get eyes on this PR today hopefully

2022-10-25 08:56 UTC, machour commented on integration/playwright-report/index.html
> +<!doctype html><html><head><meta charset="UTF-8"><meta name="color-scheme" content="dark light"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Playwright Test Report</title
This needs to be removed

2022-10-25 11:12 UTC, maxschwarzmueller commented on integration/playwright-report/index.html
> +<!doctype html><html><head><meta charset="UTF-8"><meta name="color-scheme" content="dark light"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Playwright Test Report</title
Done

2022-10-25 16:13 UTC, maxschwarzmueller commented
I'm aware of the `<form>` default and spec. But Remix documentation clearly states that Remix `<Form>` supports `DELETE`, `PATCH` etc. in addition to `GET`& `POST`: https://remix.run/docs/en/v1/api/remix#form-method

2022-10-25 16:35 UTC, chaance commented
We definitely shouldn't break existing behavior, so limiting `<Form>` to `GET` and `POST` would need to be considered in a future major release. Probably worth opening a discussion for that if that's something you feel strongly about, as we have no plans for that at the moment. This is an intentional deviation from the basic `<form>` as noted in the docs. The no-JS tests should reflect those differences for now.

2022-10-25 16:43 UTC, MichaelDeBoey approved these changes

2022-10-25 18:52 UTC, chaance commented
> As for other methods, those are great points on the docs and breaking changes. I wonder if we should more strongly discourage their usage (e.g. in dev mode do a console.warn)? One of Remix' big selling points is that it works before/without JavaScript, and this violates that.

Would you like to start a new discussion on that? I think there's merit and I'd be happy to run it up the flag pole (aka get @ryanflorence to weigh in since his GH notifications are a tire fire 😂)

2022-10-25 18:55 UTC, jenseng commented
Sure thing, will do 👍

On Tue, Oct 25, 2022 at 12:52 PM Chance Strickland ***@***.***>
wrote:

> As for other methods, those are great points on the docs and breaking
> changes. I wonder if we should more strongly discourage their usage (e.g.
> in dev mode do a console.warn)? One of Remix' big selling points is that it
> works before/without JavaScript, and this violates that.
>
> Would you like to start a new discussion on that? I think there's merit
> and I'd be happy to run it up the flag pole (aka get @ryanflorence
> <https://github.com/ryanflorence> to weigh in since his GH notifications
> are a tire fire 😂)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/remix-run/remix/pull/4413#issuecomment-1291000963>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2XMKOBUT24MVM5XQ6LS3WFAT7JANCNFSM6AAAAAARNVVQIQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-25 19:58 UTC, jenseng commented
Opened a discussion [here](https://github.com/remix-run/remix/discussions/4420)

2022-10-26 17:21 UTC, chaance approved these changes

2022-10-26 17:21 UTC, merged

2022-10-26 23:28 UTC, chaance commented
Should be fixed in `1.7.4-pre.0`. We'll get a stable release out tomorrow.