Added loaders config for 3d models
remix-run/remix pull request #4457
Opened 2022-10-31 04:57 UTC by ikarus-akhil

Adds support for importing `.glb`, `.gltf` and `.hdr` files.

Closes: #4430 

### Testing Strategy:
I was able to import `.glb` and `.hdr` files and use them in google model viewer linked using its CDN.

``` js
import model from "../../public/mod/Hololens.glb";
import env from "../../public/mod/Neutral.hdr";
const Model = () => {
  return (
    <model-viewer
      style={{ height: "100vh", width: "100vw" }}
      src={model}
      shadow-intensity="1"
      camera-controls
      touch-action="pan-y pinch-zoom"
      environment-image={env}
      camera-orbit="calc(-0.25rad + env(window-scroll-y) * 12rad) calc(90deg + env(window-scroll-y) * 45deg) calc(10m - env(window-scroll-y) * 10m)"
    />
  );
};
export default Model;
```

2022-10-31 07:38 UTC, machour requested changes
Thank you for your PR 🙏
We also need you to generate the changeset, see the comment added by the bot on the PR.

2022-10-31 07:38 UTC, machour commented on packages/remix-dev/modules.ts
> +declare module "*.glb" {
Same thing here for the order please

2022-10-31 07:38 UTC, machour commented on packages/remix-dev/compiler/loaders.ts
> +  ".hdr": "file",
Could you keep the list alphabetically sorted ?

2022-11-04 11:27 UTC, ikarus-akhil commented
@machour Have made the appropriate changes.

2022-11-08 11:17 UTC, ikarus-akhil commented
@machour Can you please review the code and approve it it is okay, as we need these loaders for our project.

2022-11-08 19:46 UTC, machour commented
@ikarus-akhil there seem to be a conflict with the changeset file, other than that looks good to me. 👌🏼 
Someone from the Remix team will eventually attend this.

In the mean time, if you can't wait any longer, I suggest using https://www.npmjs.com/package/patch-package to apply these changes on your project.

You might also be interested in this proposal https://github.com/remix-run/remix/discussions/4549 that will turn into an RFC soon and hopefully make it to Remix.

2022-12-19 12:06 UTC, ikarus-akhil commented
@machour  I have resolved the conflict, can you please merge this code.

2022-12-19 13:25 UTC, machour requested changes
Something is wrong with the changesets, it seems you edited an old one and included it again as new?

2022-12-29 08:53 UTC, ikarus-akhil commented
@machour Sorry for the delay and all the trouble, was having problem with the changeset but now I think it should be good.

2023-02-09 12:15 UTC, chaance commented
Looks like this was shipped in 1.11, resolved in https://github.com/remix-run/remix/pull/5030. I'm going to close this but I'll add @ikarus-akhil to our contributors list since we dropped the ball on reviewing in a timely manner. Sorry about that!

2023-02-09 12:15 UTC, closed without merging