Redirects when multiple slashes
remix-run/remix pull request #4622
Opened 2022-11-16 21:15 UTC by ErimTuzcuoglu

Closes: #4422

- [ ] Docs
- [x] Tests

Testing Strategy: New and existing tests pass. We can try slashed routes manually.

2022-11-16 21:32 UTC, machour commented on packages/remix-express/server.ts
> +      if(req.url !== cleanUrl) return res.redirect(cleanUrl);
```suggestion
      if (req.url !== cleanUrl) {
        return res.redirect(cleanUrl);
      }
```

2022-11-16 21:36 UTC, ErimTuzcuoglu commented on packages/remix-express/server.ts
> +      if(req.url !== cleanUrl) return res.redirect(cleanUrl);
Updated

2022-11-17 16:27 UTC, brophdawg11 commented
Is this something we need to consider for servers/runtimes other than express?

2022-11-18 11:24 UTC, machour requested changes
@ErimTuzcuoglu can you please fix the conflict in the contributors files? 🙏🏼 
Protip: put your name in the right spot alphabetically, conflicts will be less likely to happen

2022-11-18 14:49 UTC, brophdawg11 commented
@ErimTuzcuoglu I didn't dig too deep, but was able to reproduce this using the Architect template as well?  I'm wondering this is something that should be handled in a more central location, or at least should this logic go into each of the adapters.  I will probably defer to one of the Remix team members here with more experience in the alternative runtimes.  @jacob-ebey @mcansh?

2022-11-18 15:12 UTC, mcansh commented
> I'm wondering this is something that should be handled in a more central location

i just tried a [github](https://github.com//mcansh//snkrs//tree//main//app) url and it resolved with the multiple slashes without redirecting - perhaps we follow suit and normalize while matching?

2022-11-18 20:40 UTC, ErimTuzcuoglu commented
The main problem is actually on URL constructor. It doesn't accept multiple slashes as a url and throws error. So when we removed slashes it works correctly, but for redirection I think we must make different implementations on adapters. As @mcansh said, on vercel we don't need any changes. But if we need I can check also other adapters and fix them too.

![image](https://user-images.githubusercontent.com/8180270/202797497-011db439-c22f-45fc-85ac-259e1f0e6ac6.png)

2022-11-18 21:23 UTC, mcansh commented
> The main problem is actually on URL constructor. It doesn't accept multiple slashes as a url and throws error. So when we removed slashes it works correctly, but for redirection I think we must make different implementations on adapters. As @mcansh said, on vercel we don't need any changes. But if we need I can check also other adapters and fix them too.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/8180270/202797497-011db439-c22f-45fc-85ac-259e1f0e6ac6.png)
> 
> 

whats interesting is that `new URL("https://github.com///")` seems to be fine ![image](https://user-images.githubusercontent.com/11698668/202804851-3ae8b440-f32e-4dfa-b703-4c47d3621664.png)

2023-01-22 15:41 UTC, machour requested changes
@ErimTuzcuoglu Please update other adapters as well and rebase this PR to latest dev 🙏🏼

2023-01-31 21:25 UTC, brophdawg11 commented
Closing in favor of https://github.com/remix-run/remix/pull/5336

2023-01-31 21:25 UTC, closed without merging