feat(remix-dev): add support for `fastly-compute-js` as `serverBuildTarget` value
remix-run/remix pull request #4860
Opened 2022-12-14 04:13 UTC by harmony7

At Fastly we have created a runtime, a server adapter, and a template for running Remix on Fastly Compute@Edge. This PR adds support for settings `serverBuildTarget` to `fastly-compute-js`, which configures compiler settings to enable their use.

Our runtime, server adapter, and template are available at:
https://github.com/fastly/remix-compute-js

These will work once this PR is accepted.

This PR adds:

* Support for `fastly-compute-js` as an accepted value for `serverBuildTarget` in `remix.config.js`. This value:
  * Sets `serverModuleFormat` to `"esm"`
  * Sets `serverPlatform` to `"neutral"`
  * Causes `esbuild` config to:
    * use `condition` value of `["worker"]`
    * use `minify` value of `true`
    * use `mainFields` value of `["browser", "module", "main"]`
  * Causes `serverBareModulesPlugin` to always bundle everything

This PR is necessary because, except for the first two subitems in the list above, these behaviors cannot be set through `remix.config.js`.

This PR also adds the new value to the documentation page for the config file.

Relates to https://github.com/remix-run/remix/discussions/4613 as well as https://github.com/remix-run/remix/discussions/2888

2022-12-14 04:31 UTC, harmony7 commented
I've also added a changeset, please let me know if this is sufficient or if it needs changing.

2022-12-14 10:45 UTC, MichaelDeBoey approved these changes
> This PR is necessary because, except for the first two subitems in the list above, these behaviors cannot be set through `remix.config.js`.

@jenseng had the same realization in https://github.com/remix-run/remix/pull/4841#issuecomment-1347476869.
I listed all places where we need additional change before we can fully deprecate `serverBuildTarget` in https://github.com/remix-run/remix/pull/4841#issuecomment-1347546697

2022-12-14 11:36 UTC, harmony7 commented
Nice, thanks.

2023-01-19 01:40 UTC, mjackson requested changes
Thanks for the PR, @harmony7. I'd like to suggest a few changes.

By way of explanation, we have decided to deprecate `serverBuildTarget` and move as much compiler config as we can into remix.config.js. This also means un-deprecating `serverModuleFormat` and `serverPlatform` which will happen soon.

We are still figuring out which other fields we will need to expose in the Remix config. But from this PR it looks like we will need at least `mainFields`, `minify`, and `conditions` options.

Again, thank you for your patience. Let's get this across the finish line!

2023-01-19 01:40 UTC, mjackson commented on packages/remix-dev/config.ts
> +    case "fastly-compute-js":
Instead of adding this line, use `serverModuleFormat` and `serverPlatform` directly in your remix.config.js in your template

2023-01-23 02:47 UTC, harmony7 commented
Thanks for your update.  I have been following #4841 as well, and your comments make sense. As soon as that one lands the code-based changes in this PR will not be necessary (However I'd still like to submit updates to the docs to make Fastly discoverable).

2023-02-02 21:16 UTC, MichaelDeBoey commented
Closing this as #4841 is now merged

Once that's released, the `fastly` template can use these new config options.

@harmony7 If you want to add the template and/or adapter to our docs like @penx did in #5254, feel free to open a new PR for that 🙏

2023-02-02 21:16 UTC, closed without merging

2023-02-03 01:27 UTC, harmony7 commented
awesome, thanks!

> @harmony7 If you want to add the template and/or adapter to our docs like @penx did in https://github.com/remix-run/remix/pull/5254, feel free to open a new PR for that

I certainly will do that =) thanks

2023-02-06 03:03 UTC, harmony7 commented
@MichaelDeBoey have filed PR #5370 .  Please take a look.