docs: fix missing link to link element
remix-run/remix pull request #502
Opened 2021-11-23 12:38 UTC by johannesbraeunig

2021-11-23 14:45 UTC, MichaelDeBoey requested changes

2021-11-23 14:45 UTC, MichaelDeBoey commented on docs/api/conventions.md
> +This is an object representation of a normal `<link {...props} />` element. [View the MDN docs for the link API](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link).
It's at the bottom of the MD file

```suggestion
This is an object representation of a normal `<link {...props} />` element. [View the MDN docs for the link API][link tag].
```

2021-11-23 17:07 UTC, johannesbraeunig commented on docs/api/conventions.md
> +This is an object representation of a normal `<link {...props} />` element. [View the MDN docs for the link API](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link).
I see! Good catch 👌

2021-11-23 17:22 UTC, MichaelDeBoey approved these changes

2021-12-03 16:11 UTC, kentcdodds approved these changes
Good catch. Thanks!

2021-12-03 16:12 UTC, merged