Add missing concerts.tsx layout route from example
remix-run/remix pull request #5181
Opened 2023-01-22 04:08 UTC by JakeGinnivan

2023-01-22 14:28 UTC, MichaelDeBoey requested changes

2023-01-22 14:28 UTC, MichaelDeBoey commented on docs/file-conventions/route-files-v2.md
> +│   └── concerts.tsx
```suggestion
│   ├── concerts.tsx
│   └── concerts_.mine.tsx
```

2023-01-22 14:29 UTC, MichaelDeBoey approved these changes

2023-01-22 14:29 UTC, merged

2023-01-23 00:59 UTC, JakeGinnivan commented
@MichaelDeBoey I think the highlighted line will need to be updated with changing the order of those files. I think the commit you added will make the layout file highlighted, not the .mine file

2023-01-23 01:42 UTC, MichaelDeBoey commented
@JakeGinnivan If you're up for it, you're welcome to create a PR to update it.