Fix/get package dependencies recursive cant find deps
remix-run/remix pull request #5310
Opened 2023-01-30 12:50 UTC by nimaa77

### Description

turns out `getDependenciesToBundle` has an issue that it can not find the package json of the passed dependency so it will skip the dependencies of that package,

that's why when you call it with a dependency you will get `my-remix-app/node_modules/package.json does not exist`

the logic of the function has some issues, if we want to get the package file

```js
  // packages/remix-dev/compiler/dependencies.ts
  
  let pkgPath = require.resolve(pkg);
  let lastIndexOfPackageName = pkgPath.lastIndexOf(pkg);
  if (lastIndexOfPackageName !== -1) {
    pkgPath = pkgPath.substring(0, lastIndexOfPackageName);
  }
  let pkgJson = path.join(pkgPath, "package.json");
  ```
  
`pkgPath.lastIndexOf(pkg)` gives us the index of the first character of the passed pkg name, but what developer intended to to was to get the last index of the pkg name so at next line when we take the substring from the pkgPath and pkgPath contains the package name as well

```js
// expected
"my-remix-app/node_modules/mdx-bundler"

// what we got
"my-remix-app/node_modules"
```

changing this alone will not solve the issue, require.resolve(pkg) some times will throw

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in my-remix-app/node_modules/@babel/runtime/package.json
```

and all that we want to do is to get the package path, so we can use this package called  `resolve-package-path` to get the package path

- [ ] Docs
- [X] Tests

Testing Strategy:

2023-01-30 13:25 UTC, nimaa77 commented
I think I need to return Array of regex patterns instead of array of package names from `getDependenciesToBundle`, something like (`return Array.from(aggregatedDeps).map((dep) => new RegExp('^' + dep + '.*'));`)

not sure tho

2023-02-25 02:26 UTC, lukebro commented
Ran into same issue, and too thought that `+ pkg.length` would be an appropriate solution.

Packages that don't have a "main" entry via exports/main is tough... Now what do you build? You have to parse your usage, just becomes a bigger mess.

Another thing to consider: the dependencies of a package need to resolve relative to that dependency, not the root of project. If a package depends on a different non-semver compatible package that ends up not being hoisted aka `node_modules/pkg-a/node_modules/pkg-b` you could tell remix to build `pkg-b`, and I'd assume it would resolve+build `node_modules/pkg-b` if it existed. It's an edge case but should be considered, as I've been bitten by this. 

I could be wrong here, but perhaps just doing the `+ pkg.length` should fix most use cases. If `require.resolve` fails to resolve due to a main entry being missing, you can continue to print the warning in the console so the dev needs to handle it manually.

2023-05-02 00:26 UTC, MichaelDeBoey commented
Hi @nimaa77!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts

2023-05-04 10:13 UTC, nimaa77 commented
@MichaelDeBoey rebased and resolved

2023-05-07 00:18 UTC, MichaelDeBoey requested changes

2023-05-07 00:18 UTC, MichaelDeBoey commented on contributors.yml
> +- krolebord
Seems like something went wrong here when rebasing 🤔

```suggestion
```

2023-05-15 08:39 UTC, nimaa77 commented
@MichaelDeBoey I applied your suggestion, thanks for the reveiew

2023-05-15 23:00 UTC, MichaelDeBoey requested changes
@nimaa77 It seems like you have some conflicts to resolve
Could you please fix them?

2023-05-25 23:23 UTC, closed without merging