Sync up release docs with react router
remix-run/remix pull request #5388
Opened 2023-02-07 21:43 UTC by brophdawg11

Sibling to https://github.com/remix-run/react-router/pull/10065

2023-02-07 22:13 UTC, MichaelDeBoey approved these changes

2023-02-07 22:15 UTC, MichaelDeBoey requested changes

2023-02-07 22:15 UTC, MichaelDeBoey commented on DEVELOPMENT.md
> +  - merge the `release-*` branch into `dev` and push it up to Github
```suggestion
  - merge the `release-*` branch into `main` and push it up to GitHub
  - merge the `release-*` branch into `dev` and push it up to GitHub
```

2023-02-08 15:14 UTC, chaance approved these changes

2023-02-09 13:23 UTC, merged