chore: update @cloudflare/workers-types to v4
remix-run/remix pull request #5425
Opened 2023-02-10 23:48 UTC by lkwr

Update the Cloudflare Workers types to the latest major.

This solve dependency installing warnings when using `@cloudflare/workers-types@^4` with remix.
There was no peer dependency for version 4 in the cloudflare packages.

2023-02-11 20:27 UTC, MichaelDeBoey requested changes

2023-02-11 20:27 UTC, MichaelDeBoey commented on .changeset/cuddly-cameras-collect.md
> +"@remix-run/cloudflare-workers": patch
```suggestion
"@remix-run/cloudflare": minor
"@remix-run/cloudflare-pages": minor
"@remix-run/cloudflare-workers": minor
```

2023-02-11 20:27 UTC, MichaelDeBoey commented on .changeset/cuddly-cameras-collect.md
> +chore: update `@cloudflare/workers-types` to v4
```suggestion
feat: support `@cloudflare/workers-types` v4
```

2023-02-24 02:23 UTC, zhuhaow commented
If possible, we should switch to v4 new importable types https://github.com/cloudflare/workerd/tree/main/npm/workers-types#importable-types and drop support of v2/v3.

The current way of referencing `@cloudflare/workers-types` doesn't work at all. Just create a new remix project with `create-remix`, run `pnpm typecheck` and it fails.

So this dependency version bump is probably not a change but a fix.

2023-03-09 01:56 UTC, MichaelDeBoey commented
As this is a breaking change, we should do that in the next major version

I created #5732, which targets `v2` branch

2023-04-27 16:03 UTC, MichaelDeBoey commented
Implemented by #5732

2023-04-27 16:03 UTC, closed without merging