[Docs] Update cookies.md
remix-run/remix pull request #5630
Opened 2023-03-02 13:09 UTC by thomasverleye

Prevent cookies from being imported to the client by adding the server suffix.

2023-03-03 06:28 UTC, machour reviewed
Thank you for this contribution. 

The file is mentioned above, do we need to update its name there as well?

2023-03-03 06:28 UTC, machour commented on docs/utils/cookies.md
> +**Note:** We recommend (for now) that you create all the cookies your app needs in `app/cookies.server.ts` and `import` them into your route modules. This allows the Remix compiler to correctly prune
```suggestion
**Note:** We recommend (for now) that you create all the cookies your app needs in `app/cookies.server.js` and `import` them into your route modules. This allows the Remix compiler to correctly prune these imports out of the browser build where they are not needed. We hope to eventually remove this caveat.
```

The .js file is mentioned above

2023-03-03 14:29 UTC, thomasverleye commented
@machour updated the docs some more:
- Changed the imports to assure the `.server` suffix is added in the other code examples;
- Changed back to `.js` extension as you suggested.

2023-03-03 14:37 UTC, machour approved these changes

2023-03-16 08:46 UTC, thomasverleye commented
@machour this one is hanging two weeks now, any idea when you people merge these kinda pr's? 🙇🏻‍♂️

2023-03-17 00:14 UTC, MichaelDeBoey requested changes

2023-03-17 00:14 UTC, MichaelDeBoey commented on docs/utils/cookies.md
> +```ts filename=app/cookies.server.js
Let's keep using TS

```suggestion
```ts filename=app/cookies.server.ts
```

2023-03-17 00:14 UTC, MichaelDeBoey commented on docs/utils/cookies.md
> +```js filename=app/cookies.server.js
```suggestion
```js filename=app/cookies.server.ts
```

2023-03-17 00:14 UTC, MichaelDeBoey requested changes

2023-03-17 00:14 UTC, MichaelDeBoey commented on docs/utils/cookies.md
> +**Note:** We recommend (for now) that you create all the cookies your app needs in `app/cookies.server.js` and `import` them into your route modules. This allows the Remix compiler to correctly prune
```suggestion
**Note:** We recommend (for now) that you create all the cookies your app needs in `app/cookies.server.ts` and `import` them into your route modules. This allows the Remix compiler to correctly prune these imports out of the browser build where they are not needed. We hope to eventually remove this caveat.
```

2023-03-17 18:09 UTC, MichaelDeBoey approved these changes

2023-04-04 12:23 UTC, thomasverleye commented
Broke this one by rebasing :/ see #5997 for new PR

2023-04-04 12:23 UTC, closed without merging