fix(typescript): Allow meta data and parentsData to be undefined
remix-run/remix pull request #5787
Opened 2023-03-14 04:33 UTC by kentcdodds

Closes: #5786

~~- [ ] Docs~~
~~- [ ] Tests~~

Testing Strategy:

I tried it locally and it seems to work 👍

2023-04-24 13:11 UTC, john-persson-polestar approved these changes

2023-04-27 14:23 UTC, aaronadamsCA commented
IMO this would be well worth a patch release, because so far migrating to meta v2 is quite dangerous without it.

2023-05-04 10:04 UTC, machour requested changes
@kentcdodds could you fix the conflicts in order to get this PR merged?

I also noticed the same problem in `packages/remix-react/routeModules.ts`, not sure why this definitions are duplicated there, but they'll need fixing too. (I had #6231 open to fix it before noticing your PR)

2023-05-04 15:19 UTC, kentcdodds commented
This is untested. Think of this as more of an issue than a PR.

2023-05-05 14:43 UTC, closed without merging