Add docs on API Development Strategy
remix-run/remix pull request #5829
Opened 2023-03-16 16:15 UTC by brophdawg11

Initial pass at future flags docs

[Rendered](https://github.com/remix-run/remix/blob/brophdawg11/future-flags-docs/docs/pages/api-development-strategy.md)

2023-03-16 17:30 UTC, brophdawg11 commented on docs/pages/api-development-strategy.md
> +![Flowchart of the decision process for how to introduce a new feature][feature-flowchart]
Image lives over in the website repo: https://github.com/remix-run/remix-website/blob/brophdawg11/future-flags/public/docs-images/feature-flowchart.png

2023-03-16 22:42 UTC, MichaelDeBoey requested changes

2023-03-16 22:42 UTC, MichaelDeBoey commented on docs/pages/api-development-strategy.md
> +- Non-Breaking + Unstable API -> `future_unstable_` flag -> Lands in v1
```suggestion
- Non-Breaking + Unstable API -> `future.unstable_` flag -> Lands in v1
```

2023-03-16 22:42 UTC, MichaelDeBoey commented on docs/pages/api-development-strategy.md
> +- Breaking + Unstable API -> `future_unstable_` flag -> `future.v2_` flag -> Lands in v2
```suggestion
- Breaking + Unstable API -> `future.unstable_` flag -> `future.v2_` flag -> Lands in v2
```

2023-03-16 22:42 UTC, MichaelDeBoey commented on docs/pages/api-development-strategy.md
> +[react-router-v6-back-compat]: https://reactrouter.com/en/main/upgrading/v5#backwards-compatibility-package
```suggestion
[react-router-v6-migration-guide]: https://reactrouter.com/upgrading/v5#introduction
[react-router-v6-back-compat]: https://reactrouter.com/upgrading/v5#backwards-compatibility-package
```

2023-03-17 17:50 UTC, MichaelDeBoey approved these changes

2023-03-17 18:52 UTC, merged