feat(server-runtime): pass AppLoadContext to handleRequest
remix-run/remix pull request #5836
Opened 2023-03-17 12:01 UTC by fernandojbf

This is the same feature change request done [here](https://github.com/remix-run/remix/pull/2045). A new [discussion](https://github.com/remix-run/remix/discussions/5314) was created to this.

My action was mainly check the changes by introduced @axel-habermaier's PR and apply them again. 

This is my first contribution, if i made something wrong please let me know.

Closes: #

- [x] Docs
- [x] Tests

Testing Strategy:

I've added unit tests on server-runtime passing loadContext to the handler.

2023-03-21 19:11 UTC, fernandojbf commented
Bahh, I've made a rebase from main :( i will fix that in a moment

2023-04-26 05:20 UTC, jacob-ebey approved these changes

2023-04-26 13:37 UTC, MichaelDeBoey requested changes

2023-04-26 13:37 UTC, MichaelDeBoey commented on .changeset/twelve-cheetahs-drive.md
> +feat(remix-server-runtime): pass `AppLoadContext` to `handleRequest`
```suggestion
pass `AppLoadContext` to `handleRequest`
```

2023-04-26 13:37 UTC, MichaelDeBoey commented on .changeset/twelve-cheetahs-drive.md
> +"@remix-run/serve": patch
```suggestion
```

2023-04-26 13:38 UTC, MichaelDeBoey approved these changes

2023-04-26 14:36 UTC, kiliman commented
I, too, would like to see the PR merged. I think it was an oversight in the initial implementation. The other other `handle*Request` functions contain the context (as they came later).

2023-04-26 14:45 UTC, merged

2023-04-26 15:38 UTC, fernandojbf commented
Thank you 🎉

2023-04-26 17:24 UTC, jacob-ebey commented
> Thank you 🎉

Thank YOU! :)