ci: dedupe yarn.lock
remix-run/remix pull request #6109
Opened 2023-04-19 22:26 UTC by mcansh

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2023-04-19 22:32 UTC, MichaelDeBoey requested changes

2023-04-19 22:32 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +name: 👔 Deduple yarn.lock
```suggestion
name: 👔 Deduplicate yarn.lock
```

2023-04-19 22:33 UTC, mcansh commented on .github/workflows/dedupe-yarn.yml
> +name: 👔 Deduple yarn.lock
quickly done on my phone 😅

2023-04-19 23:02 UTC, MichaelDeBoey approved these changes
LGTM! 😍

#6108 still needs to be merged though

2023-04-19 23:02 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +          token: ${{ secrets.FORMAT_PAT }}
We don't need to pass `token` if we set write permissions (like we do in `no-response`) I think 🤔

2023-04-20 00:26 UTC, mcansh commented
> LGTM! 😍
> 
> 
> 
> #6108 still needs to be merged though

i'll check it out in the morning, didnt want to just yolo approve from my phone on this one

2023-08-07 19:13 UTC, MichaelDeBoey requested changes
Let's keep this consistent with remix-run/react-router#10583 and remix-run/examples#248 & remix-run/examples#263

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +jobs:
```suggestion
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +
```suggestion
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +
```suggestion
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +      - name: 👔 Dedupe yarn.lock
```suggestion
      - name: ️️⚙️ Dedupe yarn.lock
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +          git config --local user.name "Remix Run Bot"
```suggestion
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +            echo "💿 no formatting changed"
```suggestion
            echo "💿 no deduplication needed"
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/dedupe-yarn.yml
> +          git commit -m "chore: dedupe yarn.lock"
```suggestion
          git commit -m "chore: deduplicate `yarn.lock`"
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/format.yml
> +
```suggestion
```

2023-08-07 19:13 UTC, MichaelDeBoey commented on .github/workflows/format.yml
>          uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FORMAT_PAT }}
```

2023-08-07 19:23 UTC, MichaelDeBoey approved these changes

2023-08-08 16:50 UTC, brophdawg11 approved these changes

2023-08-08 16:50 UTC, merged