feat(deployment): add restify adapter
remix-run/remix pull request #615
Opened 2021-11-24 23:50 UTC by jenseng

copy-pasta/tweaked from express adapter

testing notes:
☑️  standard adapter tests, plus some more stream ones
☑️  generated a restify-remix app via create-remix and manually verified

lmk if there's anything I should add :)

2021-11-25 00:53 UTC, w3bdesign approved these changes

2021-12-02 21:18 UTC, MichaelDeBoey approved these changes

2021-12-02 21:18 UTC, MichaelDeBoey commented on packages/create-remix/templates/restify/remix.config.js
> +  browserBuildDirectory: "public/build",
```suggestion
  assetsBuildDirectory: "public/build",
```

See #587

2021-12-02 21:18 UTC, MichaelDeBoey commented on packages/remix-restify/__tests__/server-test.ts
> +        return new Response("", { status: 204 });
```suggestion
        return new Response(null, { status: 204 });
```

See #847

2021-12-02 21:18 UTC, MichaelDeBoey commented on packages/remix-restify/__tests__/server-test.ts
> +        return new Response("", { headers });
```suggestion
        return new Response(null, { headers });
```

See #847

2021-12-02 21:19 UTC, MichaelDeBoey requested changes

2021-12-02 21:19 UTC, MichaelDeBoey commented on packages/create-remix/templates/restify/remix.config.js
> +  browserBuildDirectory: "public/build",
```suggestion
  assetsBuildDirectory: "public/build",
```

See #587

2021-12-02 21:19 UTC, MichaelDeBoey commented on packages/remix-restify/__tests__/server-test.ts
> +        return new Response("", { status: 204 });
```suggestion
        return new Response(null, { status: 204 });
```

See #847

2021-12-02 21:19 UTC, MichaelDeBoey commented on packages/remix-restify/__tests__/server-test.ts
> +        return new Response("", { headers });
```suggestion
        return new Response(null, { headers });
```

See #847

2021-12-02 21:44 UTC, jenseng commented
Thanks @MichaelDeBoey, I made those changes

2021-12-15 18:01 UTC, ryanflorence commented
Hey Jon, we're still figuring out the plan for surfacing adapters for all the things without taking on the maintenance burden of having them all in the remix source. I've got an internal note of this PR.

I think the plan is to have a doc that points to all community adapters. You want to publish this yourself somewhere and then we'll make sure it's in the doc when we publish it? (won't be until after the break.)

2021-12-15 18:01 UTC, closed without merging

2021-12-15 18:13 UTC, jenseng commented
Sure, works for me 👍