chore: update how `REMIX_LOCAL_BUILD_DIRECTORY` is resolved
remix-run/remix pull request #6150
Opened 2023-04-24 16:09 UTC by mcansh

```diff
- REMIX_LOCAL_BUILD_DIRECTORY=../../../../some-app yarn build --tsc
+ REMIX_LOCAL_BUILD_DIRECTORY=~/some-app yarn build --tsc
```

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2023-05-26 05:05 UTC, pcattori requested changes

2023-05-26 05:05 UTC, pcattori commented on rollup.utils.js
>      process.cwd(),
```suggestion
```

2023-07-10 19:10 UTC, brophdawg11 commented
It doesn't look like `~` expansion will work quite right, but I think that's fine - I always use relative pathing anyway (https://stackoverflow.com/questions/21077670/expanding-resolving-in-node-js).

I updated this to use just `LOCAL_BUILD_DIRECTORY` instead of `REMIX_LOCAL_BUILD_DIRECTORY` as well to align with React Router (and shorted it by a few chars)

2023-07-10 19:10 UTC, brophdawg11 approved these changes

2023-07-11 02:10 UTC, pcattori approved these changes

2023-07-11 14:09 UTC, merged