Fix v2 dev server hang on Windows
remix-run/remix pull request #6538
Opened 2023-06-06 07:02 UTC by xHomu

Fixes #6504 

This is an issue noted on Epic Stack as well, forcing a patch with `execa`:

* https://github.com/epicweb-dev/epic-stack/blob/main/server/dev-server.js#L9
* https://github.com/epicweb-dev/epic-stack/issues/136

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

2023-06-06 21:58 UTC, MichaelDeBoey approved these changes

2023-06-06 22:58 UTC, pcattori requested changes

2023-06-06 22:58 UTC, pcattori commented on packages/remix-dev/devServer_unstable/index.ts
> +        shell: true,
Looks like `shell: true` is [not required for this](https://github.com/remix-run/remix/issues/6504#issuecomment-1565937262)

```suggestion
```

2023-06-06 22:58 UTC, pcattori commented on packages/remix-dev/devServer_unstable/index.ts
> +        stdio: ['ignore', 'inherit', 'inherit'],
Pretty sure we need `pipe` so that we can check for app ready messages in stdout, right @jacob-ebey ?

2023-06-06 23:05 UTC, pcattori commented on packages/remix-dev/devServer_unstable/index.ts
> +        stdio: ['ignore', 'inherit', 'inherit'],
Actually, I think we can use a [similar approach as our HMR tests](https://github.com/remix-run/remix/blob/main/integration/hmr-test.ts#L246-L250) to inspect `stdout` without needing `pipe`s for `execa` at all. @jacob-ebey let's chat about this when I'm back

2023-06-07 00:02 UTC, xHomu commented
Looks like the `stdio: ['ignore', 'inherit', 'inherit'],` fix is still necessary for v1.17.0. Otherwise tsx watch will keep looping indefinitely:

![image](https://github.com/remix-run/remix/assets/84349818/2f439359-0d46-403e-9397-6d8327ef4d92)

2023-06-07 17:25 UTC, pcattori commented
@xHomu thanks for the PR and all the investigative work! Now I understand the problem clearly. I think it will be easiest to use `inherit` for everything and then use `.on('data', ...)` listener for the dev ready messages. Planning to make a PR with what I have in mind and will share that with you.

2023-06-10 08:00 UTC, onemen reviewed
can you make sure that you don't need `shell: true` for all platforms
see [epic-stack #136](https://github.com/epicweb-dev/epic-stack/issues/136 )

2023-06-10 12:58 UTC, onemen commented
maybe it is related to tsx [#184](https://github.com/esbuild-kit/tsx/issues/184) or [#163](https://github.com/esbuild-kit/tsx/issues/163)

2023-06-10 18:14 UTC, pcattori commented
@xHomu can you reproduce the issue with any other tool (e.g. `ts-node` or something like that?) to determine if this is a `tsx` issue (and not a Remix issue)?

2023-06-10 19:59 UTC, xHomu commented
> @xHomu can you reproduce the issue with any other tool (e.g. `ts-node` or something like that?) to determine if this is a `tsx` issue (and not a Remix issue)?

Looks like ts-node with nodemon watch works, and with the swc plugin for ts-node we can mostly make up the performance difference.  I put together a reproduction repo:

* https://github.com/xHomu/epic-stack-tsx-watch-bug

## Main - vanilla Epic Stack

Currently over at Epic Stack, they worked around this Remix issue with `tsx watch` by running it as a child process:

https://github.com/xHomu/epic-stack-tsx-watch-bug/blob/main/server/dev-server.js

![image](https://github.com/remix-run/remix/assets/84349818/d912b8ac-6e10-4d4d-bf0e-2b286eb5e8bd)

## Running tsx directly

* https://github.com/xHomu/epic-stack-tsx-watch-bug/commit/4f4131bf0d6878f9c3a7bb283accebc2b7099593

![image](https://github.com/remix-run/remix/assets/84349818/d2170f89-4a72-470a-a222-883c42d27efc)

Work around by editing `node_modules\@remix-run\dev\dist\devServer_unstable\index.js` line 139:

![image](https://github.com/remix-run/remix/assets/84349818/fab31602-e52c-4fd4-ab36-ca6bd875bae9)

## ts-node alternative

* Diff: https://github.com/xHomu/epic-stack-tsx-watch-bug/commit/5adaccdb7307365b3daf3bad2c3d33d37b70c8dc

ts-node with nodemon doesn't experience the same issue as `tsx watch`:

![image](https://github.com/remix-run/remix/assets/84349818/8bd797ea-0fd8-407a-ab94-606b774e9dee)

We can mostly make up the performance difference with the swc plugin by adding `{ "ts-node": { "swc": true } }` to `tsconfig.json`.

2023-06-13 18:28 UTC, pcattori commented
@xHomu given that other tools like `ts-node` work, this seems to be a `tsx` issue, and not a Remix issue, correct?

2023-06-13 18:31 UTC, closed without merging