Fix typo in manifest regex
remix-run/remix pull request #6885
Opened 2023-07-19 21:17 UTC by lpsinger

The character class `[A-f0-9]` contains a typo: the manifest versions are upper-case hex strings.

This fixes the following CodeQL warning:
https://codeql.github.com/codeql-query-help/javascript/js-overly-large-range/

2023-07-20 16:18 UTC, pcattori commented
I think the `A-f` range is intentional as lowercased hex strings are present in manifest versions:

<img width="593" alt="Screenshot 2023-07-20 at 12 18 33 PM" src="https://github.com/remix-run/remix/assets/1477317/2fcf317b-a099-488c-929b-b439a8ed354a">

Plus the integration tests that look for those patterns are now timing out with the proposed changes.

2023-07-20 16:41 UTC, lpsinger commented
> I think the `A-f` range is intentional as lowercased hex strings are present in manifest versions:

How very odd. In my Remix 1.19.0 architect project, the filenames have uppercase manifest versions. What hosting target are you using?

2023-08-08 19:13 UTC, pcattori requested changes

2023-08-08 19:13 UTC, pcattori commented on packages/remix-dev/devServer_unstable/index.ts
> +                str && str.matchAll(/\[REMIX DEV\] ([A-F0-9]+) ready/g);
```suggestion
                str && str.matchAll(/\[REMIX DEV\] ([A-Fa-f0-9]+) ready/g);
```

2023-08-08 19:14 UTC, pcattori requested changes

2023-08-08 19:14 UTC, pcattori commented on templates/arc/plugin-remix.js
> +        const manifestMatches = contents.matchAll(/manifest-([A-F0-9]+)\.js/g);
```suggestion
        const manifestMatches = contents.matchAll(/manifest-([A-Fa-f0-9]+)\.js/g);
```

2023-08-08 19:14 UTC, pcattori approved these changes

2023-08-08 19:42 UTC, merged

2023-08-08 21:36 UTC, lpsinger commented
@pcattori, did we ever find a reason why in my testing the fingerprints were always uppercase but on yours they were lowercase or mixed case? I just have a lingering worry that there might be another bug there, or at least an inconsistency between different hosting targets.

2023-08-08 22:40 UTC, pcattori commented
Could be an OS-related thing (case-sensitive vs case-insensitive filesystems?), but not sure. If it comes up, we can create a separate issue.

2023-09-05 17:09 UTC, lpsinger commented
> @lpsinger I've tracked this down! Looks like `plugin-remix.js` is grabbing the build hash from `public/build/manifest-<HASH>.js` filename, whereas the rest of the code is looking at the _contents_ of that file, specifically the `assets.version` field.
> 
> Turns out that [`esbuild` uppercases the build hash when including it as part of a filename](https://github.com/evanw/esbuild/issues/1529). By lowercasing that hash before logging it via `logDevReady`, Remix HMR are flowing correctly.

Wouldn't it be more consistent to have `plugin-remix.js` check the file contents?

2023-09-05 20:03 UTC, pcattori commented
> Wouldn't it be more consistent to have `plugin-remix.js` check the file contents?

💯 agreed. I already have the change locally but haven't pushed it up as a PR since I've got a couple other fixes I was investigating.