templates: ignore entire build directory
remix-run/remix pull request #7177
Opened 2023-08-15 22:17 UTC by MichaelDeBoey

I originally just wanted to ignore the `metafile.*` files, but since the entire build directory is generated I figured it would be better to ignore it entirely 🤷‍♂️

2023-08-16 13:05 UTC, lpsinger requested changes

2023-08-16 13:05 UTC, lpsinger commented on templates/arc/.gitignore
> +/server
The file config.arc is under version control in the /server directory. If you want to ignore the whole server directory, then I suggest that you move the `@aws` section to app.arc and remove config.arc.

2023-08-16 14:57 UTC, MichaelDeBoey commented on templates/cloudflare-pages/.gitignore
> +/functions
By default there are no other functions except the generated ones

People can also always unignore certain files if they want to

2023-08-16 15:13 UTC, lpsinger approved these changes

2023-08-22 16:41 UTC, pcattori commented on templates/cloudflare-pages/.gitignore
> +/functions
I agree that we should try to target only the Remix-generated functions in the gitignore

2023-08-22 17:05 UTC, MichaelDeBoey commented on templates/cloudflare-pages/.gitignore
> +/functions
@pcattori I assume only if we by default choose for another folder than `build` (which is the default build folder)?

2023-08-22 21:02 UTC, pmbanugo approved these changes
✨

2023-08-23 17:41 UTC, pcattori approved these changes

2023-08-23 17:41 UTC, merged