feat(dev): improve minified CSS compatibility
remix-run/remix pull request #7187
Opened 2023-08-16 23:52 UTC by markdalgleish

Fixes #6114

As the changeset says, we now minify CSS targeting the Remix browser support baseline (i.e. anything that supports [ES module scripts](https://caniuse.com/es6-module)), whereas previously CSS was minified using esbuild's default "esnext" target. This meant that CSS in the production build could be using properties that are unsupported in some browsers.

This change also means you now have more control over CSS transformations using the built-in PostCSS support since they won't be reversed by esbuild's minification.

2023-08-17 22:54 UTC, MichaelDeBoey requested changes

2023-08-17 22:54 UTC, MichaelDeBoey commented on packages/remix-dev/compiler/css/bundle.ts
> +interface GroupedCssBundleFiles {
This can just be a `type` I guess?

```suggestion
type GroupedCssBundleFiles = {
```

2023-08-18 11:12 UTC, MichaelDeBoey approved these changes

2023-08-18 15:51 UTC, pcattori approved these changes

2023-08-18 23:32 UTC, merged