feat(remix-dev): support root route as a folder
remix-run/remix pull request #7256
Opened 2023-08-25 15:35 UTC by lpsinger

Closes: #7033

- [x] Docs
- [x] Tests

Testing Strategy: added new integration test

2023-08-26 20:46 UTC, MichaelDeBoey requested changes

2023-08-26 20:46 UTC, MichaelDeBoey commented on integration/root-route-folder-test.ts
> +      },
```suggestion
```

2023-09-02 19:57 UTC, lpsinger commented
I rebased.

2023-11-01 15:55 UTC, MichaelDeBoey requested changes

2023-11-01 15:55 UTC, MichaelDeBoey commented on docs/file-conventions/routes.md
> +```
```suggestion
```text
app/
├── root/
|   ├── footer.tsx
|   ├── menu.tsx
|   └── route.tsx
└── routes/
    ├── _index.tsx
    └── about.tsx
```
```

2025-05-26 14:53 UTC, closed without merging