Fix comment on default for serverModuleFormat
remix-run/remix pull request #7536
Opened 2023-09-25 23:44 UTC by ngbrown

Since the default for `serverModuleFormat` is now `esm`, the comments in the v2 guide for the different configurations of `serverBuildTarget` were incorrect.

- [x] Docs

2023-09-27 14:30 UTC, brophdawg11 commented
These comments are tricky since they are intended (originally) for v1 users preparing for v2.  So CJS is still the default on v1.  Now that v2 is released, ESM is the default but there are still 2 types of users reading these docs:

* Users upgrading to `1.19.x` and adopting all future flags to smooth the v2 upgrade
  * Current comments are accurate for these folks 
* Users going straight to v2 without the in-between step
  * Your proposed new comments are accurate for these folks

I think it's probably best to either remove these specific comments or change them to `default value in 1.x`/`default value in 2.x` for clarity?

2023-09-27 17:56 UTC, ngbrown commented
> These comments are tricky since they are intended (originally) for v1 users preparing for v2. So CJS is still the default on v1. Now that v2 is released, ESM is the default but there are still 2 types of users reading these docs:
> 
> * Users upgrading to `1.19.x` and adopting all future flags to smooth the v2 upgrade
>   
>   * Current comments are accurate for these folks

Yes, I considered that, but the document is, at some level, upgrading a user to v2, not to v1.9 with the v2 flags. For users that are upgrading to v1.9 with all flags enabled, would be best served to use the v1.9 documentation.

2023-09-28 12:47 UTC, brophdawg11 commented
> but the document is, at some level, upgrading a user to v2

If the document were _only_ intended to be read by users upgrading straight to v2, then it wouldn't include the steps of telling them to set `future.v2_*` flags to true since those flags don't exist in v2.  Successfully or not, at the moment it is intentionally trying to be something consumable by both sets of users I mentioned above.

> would be best served to use the v1.19 documentation

In an ideal world, yes.  But in practice these users are going to land on the `main` docs and the vast majority of them won't know/remember to switch over to the v1.x docs, so we have to be pragmatic.

2023-09-28 16:02 UTC, machour requested changes
Thank you for your contribution!

Seconding Matt's suggestion here, using `default value in 1.x/default value in 2.x` would help avoid any confusion

2023-09-28 17:36 UTC, ngbrown commented
I updated the comments to the following:
```ts
serverModuleFormat: "cjs", // default value in 1.x, add before upgrading
...
serverModuleFormat: "esm", // default value in 2.x, can be removed once upgraded
```

2023-10-02 15:24 UTC, brophdawg11 approved these changes

2023-10-02 15:25 UTC, merged