[WIP] Add experimental Vite support
remix-run/remix pull request #7590
Opened 2023-10-05 03:01 UTC by markdalgleish

2023-10-11 18:24 UTC, OnurGvnc commented
[hono](https://hono.dev/) has a vite-dev-server that is compatible with cloudflare workers. I don't know all the details, but here are some links that might give an idea about cloudflare workers compatibility
- https://www.npmjs.com/package/@hono/vite-dev-server
- https://github.com/honojs/vite-plugins/tree/main/packages/dev-server
- https://github.com/honojs/vite-plugins/blob/f5d4c78cfc94b4e46f9dd191f1cd07da832cdee5/packages/dev-server/src/dev-server.ts#L46-L53
- https://github.com/yusukebe/vite-dev-server-examples/blob/main/src/index.ts

maybe related:
- https://github.com/cloudflare/miniflare/pull/639
- https://github.com/leader22/cfw-bindings-wrangler-bridge
- https://github.com/james-elicx/cf-bindings-proxy

2023-10-13 03:29 UTC, pcattori requested changes

2023-10-13 03:29 UTC, pcattori commented on docs/future/vite.md
> +[Vite] is a powerful, performant and extensible development environment for JavaScript projects. In order to improve and extend Remix's bundling capabilities, we're currently exploring the use of Vit
```suggestion
[Vite][vite] is a powerful, performant and extensible development environment for JavaScript projects. In order to improve and extend Remix's bundling capabilities, we're currently exploring the use of Vite as an alternative compiler to esbuild.
```

2023-10-13 03:34 UTC, pcattori requested changes

2023-10-13 03:34 UTC, pcattori commented on docs/future/vite.md
> +To use [Tailwind] in Vite, first install the required dependencies:
Missing link:

```suggestion
To use [Tailwind][tailwind] in Vite, first install the required dependencies:
```

2023-10-13 03:40 UTC, pcattori requested changes

2023-10-13 03:40 UTC, pcattori commented on docs/future/vite.md
> +<docs-info>You may even want to take this a step further and create a [remark plugin][remark-plugin] that automatically maps frontmatter to route exports for you.</doc-info>
```suggestion
```

2023-10-13 03:44 UTC, pcattori requested changes

2023-10-13 03:44 UTC, pcattori commented on docs/future/vite.md
> +Since Vite leverages ESM at runtime to load modules, you may need to use `import *` when importing server/client-only files if the import statement hasn't been removed by dead code elimination.
```suggestion
```

2023-10-13 03:46 UTC, pcattori requested changes

2023-10-13 03:46 UTC, pcattori commented on docs/future/vite.md
> +export const action = () => {}; // ✅
```suggestion

// these exports are treeshaken by Remix, so they never affect HMR
export const headers = { "Cache-Control": "max-age=3600" }; // ✅
export const loader = () => {}; // ✅
export const action = () => {}; // ✅
```

2023-10-13 03:52 UTC, pcattori approved these changes

2023-10-13 04:26 UTC, pcattori requested changes

2023-10-13 04:26 UTC, pcattori commented on docs/future/vite.md
> +export const action = () => {}; // ✅
Headers is server-only:

```suggestion
// These exports are handled by the Remix Vite plugin
// to be HMR-compatible
export const meta = { title: "Home" }; // ✅
export const links = [
  { rel: "stylesheet", href: "style.css" },
]; // ✅

// These exports are removed by the Remix Vite plugin
// so they never affect HMR
export const headers = { "Cache-Control": "max-age=3600" }; // ✅
export const loader = () => {}; // ✅
export const action = () => {}; // ✅
```

2023-10-13 04:26 UTC, pcattori commented on docs/future/vite.md
> +export const action = () => {}; // ✅
outdated. added a [separate suggestion here](https://github.com/remix-run/remix/pull/7590#discussion_r1357743458)

2023-10-13 16:13 UTC, pcattori approved these changes

2023-10-13 16:33 UTC, merged

2023-10-30 11:32 UTC, mmachatschek commented
@pcattori where should issues be reported?

2023-10-31 02:20 UTC, pcattori commented
Yea separate issue with "Vite Nightly" or something like that is the way to go