chore: update dependencies to latest minor
remix-run/remix pull request #785
Opened 2021-11-29 21:32 UTC by MichaelDeBoey

2021-11-29 21:36 UTC, MichaelDeBoey commented on packages/create-remix/templates/arc/package.json
> +    "@architect/architect": "^8.7.4",
`@remix-run/architect` has this as a `peerDependency`

2021-11-29 21:36 UTC, MichaelDeBoey commented on packages/create-remix/templates/vercel/package.json
> +    "@vercel/node": "^1.12.1"
`@remix-run/vercel ` has this as a `peerDependency`

2021-11-29 21:36 UTC, MichaelDeBoey commented on packages/remix-cloudflare-workers/package.json
>      "@remix-run/server-runtime": "1.0.6"
`@remix-run/server-runtime` has `react` & `react-dom` as `peerDependency`.
Should we add them as dependencies or peerDependencies in this package too?

2021-12-07 23:26 UTC, MichaelDeBoey commented
@kentcdodds Is there something I should still do to get this one merged?

2022-01-11 17:18 UTC, kentcdodds requested changes
Thanks for this, but we're a bit concerned about this in the `npm-check-updates` docs:

> npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions

We don't want to ignore specified versions. So I don't think we're going to merge this. We'll update deps manually on an as-needed basis. Thanks for taking the time anyway!

2022-01-11 17:18 UTC, closed without merging

2022-01-11 17:22 UTC, MichaelDeBoey commented
@kentcdodds Since I used the `--minor` flag, these weren't ignored

I can remove the script if you want btw.

2022-01-11 18:00 UTC, kentcdodds commented
I think we'll come back to this when we're more confident in our testing infra. Thank you for writing the script. It may be needed in the future! Thanks!