Fix routing guide link
remix-run/remix pull request #842
Opened 2021-12-02 03:11 UTC by RobinClowers

I noticed the link the guide on nested routes was broken, so I fixed it. Loving remix so far, thanks for open sourcing it!

2021-12-02 21:05 UTC, MichaelDeBoey requested changes

2021-12-02 21:05 UTC, MichaelDeBoey commented on examples/basic/app/routes/demos/about.tsx
> +          <a href="https://remix.run/docs/en/v1/guides/routing">
```suggestion
          <a href="https://remix.run/guides/routing">
```

See #778

2021-12-02 21:05 UTC, MichaelDeBoey commented on examples/blog-tutorial/app/routes/demos/about.tsx
> +          <a href="https://remix.run/docs/en/v1/guides/routing">
```suggestion
          <a href="https://remix.run/guides/routing">
```

See #778

2021-12-02 21:05 UTC, MichaelDeBoey commented on packages/create-remix/templates/_shared_js/app/routes/demos/about.jsx
> +          <a href="https://remix.run/docs/en/v1/guides/routing">
```suggestion
          <a href="https://remix.run/guides/routing">
```

See #778

2021-12-02 21:05 UTC, MichaelDeBoey commented on packages/create-remix/templates/_shared_ts/app/routes/demos/about.tsx
> +          <a href="https://remix.run/docs/en/v1/guides/routing">
```suggestion
          <a href="https://remix.run/guides/routing">
```

See #778

2021-12-05 23:38 UTC, RobinClowers commented
@MichaelDeBoey Thanks for the review, I fixed that issue, should be good to merge now.

2022-02-11 18:42 UTC, ryanflorence commented
We're actually planning to just rewrite this whole guide soon and the templates have changed. Sorry for getting to this so late and thank you for taking the time to send this!

2022-02-11 18:42 UTC, closed without merging