docs: update *.server.tsx to *.server.ts
remix-run/remix pull request #8789
Opened 2024-02-19 12:39 UTC by alcpereira

- [x] Docs

# Description

While reading the [Route File Naming docs](https://remix.run/docs/en/main/file-conventions/routes#folders-for-organization) , I got confused by the route examples `.server.tsx`. The names of the files implie no JSX return, so I guess it should be a `.server.ts` file instead.

Even more, if you read the [docs](https://remix.run/docs/en/main/file-conventions/-server) for `*.server.ts`, it doesn't mention the `tsx` extension.

While it seems that both `.tsx` and `.ts` work (haven't thoroughly checked tho), I think those examples should be a `.ts` extension to reinforce the idea of extract colocating logic next to components, like Ryan brilliantly explained in [this video](https://www.youtube.com/watch?v=xEl8OCMOf_I).

## Note
I also changed `.client.tsx` to `.client.ts` in the `server-vs-client.md` file as I thought it would be even more confusing to have `*.client.tsx` and `*.server.ts` in the same paragraph. 

Should we add some more details in the `file_convention` docs regarding the extensions?

2024-02-19 12:46 UTC, MichaelDeBoey requested changes

2024-02-19 12:47 UTC, alcpereira commented on docs/guides/file-uploads.md
> +```tsx filename=file-upload-handler.server.ts
Good catch 😅 Thanks!

2024-02-21 01:20 UTC, MichaelDeBoey approved these changes

2024-02-26 02:53 UTC, markdalgleish approved these changes

2024-02-26 02:54 UTC, merged