fix: use document over window for browser check
remix-run/remix pull request #984
Opened 2021-12-10 22:25 UTC by jacob-ebey

Runtimes such as Deno have a window defined making this check not work.

2021-12-10 22:50 UTC, mjackson requested changes

2021-12-10 22:50 UTC, mjackson commented on docs/other-api/constraints.md
>  #### Window Guard
Let's change this to say "Document Guard"

2021-12-10 22:50 UTC, mjackson commented on docs/other-api/constraints.md
> +This ensures the library is only initialized if there is a `document`, meaning you're in the browser. We recomend `document` over `window` because server runtimes like Deno have a global `window` ava
s/server runtimes like Deno have/Deno has/

2021-12-10 23:46 UTC, mcansh approved these changes

2021-12-12 00:00 UTC, kentcdodds approved these changes
Perfect

2021-12-12 00:02 UTC, merged

2021-12-15 10:15 UTC, btargac commented
Does remix run on Deno instead of Node runtime ?

2021-12-15 10:16 UTC, girishk21 commented
> Does remix run on Deno instead of Node runtime ?

https://twitter.com/ebey_jacob/status/1471009211416932353?s=20 it does, and it runs really well 😄 . The official adapter should land soon I guess

2021-12-15 10:39 UTC, kentcdodds commented
It runs on both and more so we need code that runs equally well on all platforms we support.