feat(dev): Chance/ignore routes files
remix-run/remix pull request #989
Opened 2021-12-11 18:16 UTC by chaance

This should be considered once https://github.com/remix-run/remix/pull/988 is merged. It introduces a new configuration API for ignoring non-route files in `app/routes`. This would allow users to keep CSS or test files adjacent to their route modules. 

```js
// remix.config.js
module.exports = {
  // ...
  // new optional config option
  ignoredRouteFiles: "*.css"
};
```

2021-12-11 19:11 UTC, mcansh approved these changes

2021-12-11 23:58 UTC, kentcdodds reviewed
This looks good code-wise with one change. Needs consensus on including the feature in the first place and could use tests

2021-12-11 23:58 UTC, kentcdodds commented on packages/remix-dev/config.ts
> +  ignoredRouteFiles?: string;
Could we make this an array of globs instead?

2021-12-12 18:45 UTC, kentcdodds approved these changes
Looks good to me. Once we decide we want this I can add some docs. Cc @mjackson and @ryanflorence 
I'm in favor of this change.

2021-12-13 20:32 UTC, ryanflorence commented
I've hesitated on this for months because I anticipated doing fancy stuff with `.css` or `.pdf`, etc. in the routes folder.

But now that we have resource routes, that seems covered.

My real question now is why have it be configuration at all? Just ignore everything except `{js,jsx,ts,tsx,md,mdx}`

2021-12-13 20:32 UTC, ryanflorence commented
oh right, test files ...

2021-12-13 21:02 UTC, chaance commented
Another thing I think that is nice about the config option is that if we do decide to do something fancy with certain file types in the future, it wouldn't break existing apps that have those file types ignored. They could simply opt-in by removing them from the ignore list.

2021-12-13 22:02 UTC, kentcdodds commented
We talked about this a bit and we're thinking that the dotfiles stuff we did earlier should actually be removed (before it's released) and people can ignore dotfiles through this. The templates could be updated to ignore dotfiles via this API as well. Can you do that @chaance?

2021-12-15 16:39 UTC, chaance commented
TBH I'm not sure how I feel about this, but I made the changes to all configs in the project to match the template defaults. Seems to add more boilerplate just to avoid a tiny bit of magic 🤷‍♂️

2021-12-15 17:05 UTC, MichaelDeBoey requested changes

2021-12-15 17:05 UTC, MichaelDeBoey commented on packages/remix-dev/config/routesConvention.ts
> +      ignoredFilePatterns.some(pattern => minimatch(file, pattern))
No need for a check if you give `ignoredFilePatterns` a default value of `[]`

```suggestion
      ignoredFilePatterns.some(pattern => minimatch(file, pattern))
```

2021-12-15 17:05 UTC, MichaelDeBoey commented on packages/remix-dev/config/routesConvention.ts
> +  ignoredFilePatterns?: string[]
```suggestion
  ignoredFilePatterns?: string[] = []
```

2021-12-15 17:05 UTC, kentcdodds approved these changes
![seal of approval](https://media.giphy.com/media/13zeE9qQNC5IKk/giphy.gif)

2021-12-15 17:16 UTC, merged